//! MRI's declared built-in method shapes — the arity, defining module and
//! parameter list of every method the reference interpreter defines on the core
//! classes.
//!
//! A built-in is native code with no written parameter list, so `Method#arity`,
//! `#owner` and `#parameters` cannot be derived from it the way a `def` allows;
//! without this table they can only report "variadic, owner unknown". Every row
//! is what the reference `ruby` reports for that method.
//!
//! GENERATED — do not edit by hand. Regenerate against the reference
//! interpreter with:
//!
//! ```text
//! ruby tools/gen_arity_table.rb > src/arity_table.rs && cargo fmt
//! ```

/// `(owner, method, arity, params)`, sorted by `(owner, method)` for binary
/// search. An empty `params` means the list is the one implied by the arity
/// (see [`params_for`]); a non-empty one is `kind[:name]`, comma separated.
pub static BUILTIN_METHODS: &[(&str, &str, i16, &str)] = &[
    ("#<Class:Array>", "[]", -1, ""),
    ("#<Class:Array>", "new", -1, ""),
    ("#<Class:Array>", "try_convert", 1, ""),
    ("#<Class:Class>", "allocate", 0, ""),
    ("#<Class:Complex>", "polar", -1, ""),
    ("#<Class:Complex>", "rect", -1, ""),
    ("#<Class:Complex>", "rectangular", -1, ""),
    ("#<Class:Data>", "define", -1, ""),
    ("#<Class:Dir>", "[]", -1, "rest:args,key:base,key:sort"),
    ("#<Class:Dir>", "chdir", -1, ""),
    ("#<Class:Dir>", "children", -1, ""),
    ("#<Class:Dir>", "chroot", 1, ""),
    ("#<Class:Dir>", "delete", 1, ""),
    ("#<Class:Dir>", "each_child", -1, ""),
    ("#<Class:Dir>", "empty?", 1, ""),
    ("#<Class:Dir>", "entries", -1, ""),
    ("#<Class:Dir>", "exist?", 1, ""),
    ("#<Class:Dir>", "fchdir", 1, ""),
    ("#<Class:Dir>", "for_fd", 1, ""),
    ("#<Class:Dir>", "foreach", -1, ""),
    ("#<Class:Dir>", "getwd", 0, ""),
    (
        "#<Class:Dir>",
        "glob",
        -2,
        "req:pattern,opt:_flags,key:flags,key:base,key:sort",
    ),
    ("#<Class:Dir>", "home", -1, ""),
    ("#<Class:Dir>", "mkdir", -1, ""),
    (
        "#<Class:Dir>",
        "open",
        -2,
        "req:name,key:encoding,block:block",
    ),
    ("#<Class:Dir>", "pwd", 0, ""),
    ("#<Class:Dir>", "rmdir", 1, ""),
    ("#<Class:Dir>", "unlink", 1, ""),
    ("#<Class:Encoding>", "_load", 1, ""),
    ("#<Class:Encoding>", "aliases", 0, ""),
    ("#<Class:Encoding>", "compatible?", 2, ""),
    ("#<Class:Encoding>", "default_external", 0, ""),
    ("#<Class:Encoding>", "default_external=", 1, ""),
    ("#<Class:Encoding>", "default_internal", 0, ""),
    ("#<Class:Encoding>", "default_internal=", 1, ""),
    ("#<Class:Encoding>", "find", 1, ""),
    ("#<Class:Encoding>", "list", 0, ""),
    ("#<Class:Encoding>", "locale_charmap", 0, ""),
    ("#<Class:Encoding>", "name_list", 0, ""),
    ("#<Class:Enumerator>", "produce", -1, ""),
    ("#<Class:Enumerator>", "product", -1, ""),
    ("#<Class:Exception>", "exception", -1, ""),
    ("#<Class:Exception>", "to_tty?", 0, ""),
    ("#<Class:Fiber>", "[]", 1, ""),
    ("#<Class:Fiber>", "[]=", 2, ""),
    ("#<Class:Fiber>", "blocking", 0, ""),
    ("#<Class:Fiber>", "blocking?", 0, ""),
    ("#<Class:Fiber>", "current", 0, ""),
    ("#<Class:Fiber>", "current_scheduler", 0, ""),
    ("#<Class:Fiber>", "schedule", -1, ""),
    ("#<Class:Fiber>", "scheduler", 0, ""),
    ("#<Class:Fiber>", "set_scheduler", 1, ""),
    ("#<Class:Fiber>", "yield", -1, ""),
    ("#<Class:File>", "absolute_path", -1, ""),
    ("#<Class:File>", "absolute_path?", 1, ""),
    ("#<Class:File>", "atime", 1, ""),
    ("#<Class:File>", "basename", -1, ""),
    ("#<Class:File>", "birthtime", 1, ""),
    ("#<Class:File>", "blockdev?", 1, ""),
    ("#<Class:File>", "chardev?", 1, ""),
    ("#<Class:File>", "chmod", -1, ""),
    ("#<Class:File>", "chown", -1, ""),
    ("#<Class:File>", "ctime", 1, ""),
    ("#<Class:File>", "delete", -1, ""),
    ("#<Class:File>", "directory?", 1, ""),
    ("#<Class:File>", "dirname", -1, ""),
    ("#<Class:File>", "empty?", 1, ""),
    ("#<Class:File>", "executable?", 1, ""),
    ("#<Class:File>", "executable_real?", 1, ""),
    ("#<Class:File>", "exist?", 1, ""),
    ("#<Class:File>", "expand_path", -1, ""),
    ("#<Class:File>", "extname", 1, ""),
    ("#<Class:File>", "file?", 1, ""),
    ("#<Class:File>", "fnmatch", -1, ""),
    ("#<Class:File>", "fnmatch?", -1, ""),
    ("#<Class:File>", "ftype", 1, ""),
    ("#<Class:File>", "grpowned?", 1, ""),
    ("#<Class:File>", "identical?", 2, ""),
    ("#<Class:File>", "join", -1, ""),
    ("#<Class:File>", "lchmod", -1, ""),
    ("#<Class:File>", "lchown", -1, ""),
    ("#<Class:File>", "link", 2, ""),
    ("#<Class:File>", "lstat", 1, ""),
    ("#<Class:File>", "lutime", -1, ""),
    ("#<Class:File>", "mkfifo", -1, ""),
    ("#<Class:File>", "mtime", 1, ""),
    ("#<Class:File>", "owned?", 1, ""),
    ("#<Class:File>", "path", 1, ""),
    ("#<Class:File>", "pipe?", 1, ""),
    ("#<Class:File>", "readable?", 1, ""),
    ("#<Class:File>", "readable_real?", 1, ""),
    ("#<Class:File>", "readlink", 1, ""),
    ("#<Class:File>", "realdirpath", -1, ""),
    ("#<Class:File>", "realpath", -1, ""),
    ("#<Class:File>", "rename", 2, ""),
    ("#<Class:File>", "setgid?", 1, ""),
    ("#<Class:File>", "setuid?", 1, ""),
    ("#<Class:File>", "size", 1, ""),
    ("#<Class:File>", "size?", 1, ""),
    ("#<Class:File>", "socket?", 1, ""),
    ("#<Class:File>", "split", 1, ""),
    ("#<Class:File>", "stat", 1, ""),
    ("#<Class:File>", "sticky?", 1, ""),
    ("#<Class:File>", "symlink", 2, ""),
    ("#<Class:File>", "symlink?", 1, ""),
    ("#<Class:File>", "truncate", 2, ""),
    ("#<Class:File>", "umask", -1, ""),
    ("#<Class:File>", "unlink", -1, ""),
    ("#<Class:File>", "utime", -1, ""),
    ("#<Class:File>", "world_readable?", 1, ""),
    ("#<Class:File>", "world_writable?", 1, ""),
    ("#<Class:File>", "writable?", 1, ""),
    ("#<Class:File>", "writable_real?", 1, ""),
    ("#<Class:File>", "zero?", 1, ""),
    ("#<Class:FileTest>", "blockdev?", 1, ""),
    ("#<Class:FileTest>", "chardev?", 1, ""),
    ("#<Class:FileTest>", "directory?", 1, ""),
    ("#<Class:FileTest>", "empty?", 1, ""),
    ("#<Class:FileTest>", "executable?", 1, ""),
    ("#<Class:FileTest>", "executable_real?", 1, ""),
    ("#<Class:FileTest>", "exist?", 1, ""),
    ("#<Class:FileTest>", "file?", 1, ""),
    ("#<Class:FileTest>", "grpowned?", 1, ""),
    ("#<Class:FileTest>", "identical?", 2, ""),
    ("#<Class:FileTest>", "owned?", 1, ""),
    ("#<Class:FileTest>", "pipe?", 1, ""),
    ("#<Class:FileTest>", "readable?", 1, ""),
    ("#<Class:FileTest>", "readable_real?", 1, ""),
    ("#<Class:FileTest>", "setgid?", 1, ""),
    ("#<Class:FileTest>", "setuid?", 1, ""),
    ("#<Class:FileTest>", "size", 1, ""),
    ("#<Class:FileTest>", "size?", 1, ""),
    ("#<Class:FileTest>", "socket?", 1, ""),
    ("#<Class:FileTest>", "sticky?", 1, ""),
    ("#<Class:FileTest>", "symlink?", 1, ""),
    ("#<Class:FileTest>", "world_readable?", 1, ""),
    ("#<Class:FileTest>", "world_writable?", 1, ""),
    ("#<Class:FileTest>", "writable?", 1, ""),
    ("#<Class:FileTest>", "writable_real?", 1, ""),
    ("#<Class:FileTest>", "zero?", 1, ""),
    ("#<Class:GC>", "auto_compact", 0, ""),
    ("#<Class:GC>", "auto_compact=", 1, ""),
    ("#<Class:GC>", "compact", 0, ""),
    ("#<Class:GC>", "config", -1, "opt:hash"),
    ("#<Class:GC>", "count", 0, ""),
    ("#<Class:GC>", "disable", 0, ""),
    ("#<Class:GC>", "enable", 0, ""),
    ("#<Class:GC>", "latest_compact_info", 0, ""),
    ("#<Class:GC>", "latest_gc_info", -1, "opt:hash_or_key"),
    ("#<Class:GC>", "measure_total_time", 0, ""),
    ("#<Class:GC>", "measure_total_time=", 1, "req:flag"),
    (
        "#<Class:GC>",
        "start",
        -1,
        "key:full_mark,key:immediate_mark,key:immediate_sweep",
    ),
    ("#<Class:GC>", "stat", -1, "opt:hash_or_key"),
    (
        "#<Class:GC>",
        "stat_heap",
        -1,
        "opt:heap_name,opt:hash_or_key",
    ),
    ("#<Class:GC>", "stress", 0, ""),
    ("#<Class:GC>", "stress=", 1, "req:flag"),
    ("#<Class:GC>", "total_time", 0, ""),
    ("#<Class:GC>", "verify_compaction_references", -1, ""),
    ("#<Class:GC>", "verify_internal_consistency", 0, ""),
    ("#<Class:Hash>", "[]", -1, ""),
    ("#<Class:Hash>", "ruby2_keywords_hash", 1, ""),
    ("#<Class:Hash>", "ruby2_keywords_hash?", 1, ""),
    ("#<Class:Hash>", "try_convert", 1, ""),
    ("#<Class:IO>", "binread", -1, ""),
    ("#<Class:IO>", "binwrite", -1, ""),
    ("#<Class:IO>", "copy_stream", -1, ""),
    ("#<Class:IO>", "for_fd", -1, ""),
    ("#<Class:IO>", "foreach", -1, ""),
    ("#<Class:IO>", "new", -1, ""),
    ("#<Class:IO>", "open", -1, ""),
    ("#<Class:IO>", "pipe", -1, ""),
    ("#<Class:IO>", "popen", -1, ""),
    ("#<Class:IO>", "read", -1, ""),
    ("#<Class:IO>", "readlines", -1, ""),
    ("#<Class:IO>", "select", -1, ""),
    ("#<Class:IO>", "sysopen", -1, ""),
    ("#<Class:IO>", "try_convert", 1, ""),
    ("#<Class:IO>", "write", -1, ""),
    ("#<Class:Integer>", "sqrt", 1, ""),
    ("#<Class:Integer>", "try_convert", 1, ""),
    ("#<Class:Kernel>", "Array", 1, ""),
    ("#<Class:Kernel>", "Complex", -1, ""),
    ("#<Class:Kernel>", "Float", -2, "req:arg,key:exception"),
    ("#<Class:Kernel>", "Hash", 1, ""),
    (
        "#<Class:Kernel>",
        "Integer",
        -2,
        "req:arg,opt:base,key:exception",
    ),
    ("#<Class:Kernel>", "Pathname", 1, "req:path"),
    ("#<Class:Kernel>", "Rational", -1, ""),
    ("#<Class:Kernel>", "String", 1, ""),
    ("#<Class:Kernel>", "__callee__", 0, ""),
    ("#<Class:Kernel>", "__dir__", 0, ""),
    ("#<Class:Kernel>", "__method__", 0, ""),
    ("#<Class:Kernel>", "`", 1, ""),
    ("#<Class:Kernel>", "abort", -1, ""),
    ("#<Class:Kernel>", "at_exit", 0, ""),
    ("#<Class:Kernel>", "autoload", 2, ""),
    ("#<Class:Kernel>", "autoload?", -1, ""),
    ("#<Class:Kernel>", "binding", 0, ""),
    ("#<Class:Kernel>", "block_given?", 0, ""),
    ("#<Class:Kernel>", "caller", -1, ""),
    ("#<Class:Kernel>", "caller_locations", -1, ""),
    ("#<Class:Kernel>", "catch", -1, ""),
    ("#<Class:Kernel>", "eval", -1, ""),
    ("#<Class:Kernel>", "exec", -1, ""),
    ("#<Class:Kernel>", "exit", -1, ""),
    ("#<Class:Kernel>", "exit!", -1, ""),
    ("#<Class:Kernel>", "fail", -1, ""),
    ("#<Class:Kernel>", "fork", 0, ""),
    ("#<Class:Kernel>", "format", -1, ""),
    ("#<Class:Kernel>", "gets", -1, ""),
    ("#<Class:Kernel>", "global_variables", 0, ""),
    ("#<Class:Kernel>", "iterator?", 0, ""),
    ("#<Class:Kernel>", "lambda", 0, ""),
    ("#<Class:Kernel>", "load", -1, ""),
    ("#<Class:Kernel>", "local_variables", 0, ""),
    ("#<Class:Kernel>", "loop", 0, ""),
    ("#<Class:Kernel>", "open", -1, ""),
    ("#<Class:Kernel>", "p", -1, ""),
    ("#<Class:Kernel>", "print", -1, ""),
    ("#<Class:Kernel>", "printf", -1, ""),
    ("#<Class:Kernel>", "proc", 0, ""),
    ("#<Class:Kernel>", "putc", 1, ""),
    ("#<Class:Kernel>", "puts", -1, ""),
    ("#<Class:Kernel>", "raise", -1, ""),
    ("#<Class:Kernel>", "rand", -1, ""),
    ("#<Class:Kernel>", "readline", -1, ""),
    ("#<Class:Kernel>", "readlines", -1, ""),
    ("#<Class:Kernel>", "require", 1, ""),
    ("#<Class:Kernel>", "require_relative", 1, ""),
    ("#<Class:Kernel>", "select", -1, ""),
    ("#<Class:Kernel>", "set_trace_func", 1, ""),
    ("#<Class:Kernel>", "sleep", -1, ""),
    ("#<Class:Kernel>", "spawn", -1, ""),
    ("#<Class:Kernel>", "sprintf", -1, ""),
    ("#<Class:Kernel>", "srand", -1, ""),
    ("#<Class:Kernel>", "syscall", 0, ""),
    ("#<Class:Kernel>", "system", -1, ""),
    ("#<Class:Kernel>", "test", -1, ""),
    ("#<Class:Kernel>", "throw", -1, ""),
    ("#<Class:Kernel>", "trace_var", -1, ""),
    ("#<Class:Kernel>", "trap", -1, ""),
    ("#<Class:Kernel>", "untrace_var", -1, ""),
    (
        "#<Class:Kernel>",
        "warn",
        -1,
        "rest:msgs,key:uplevel,key:category",
    ),
    ("#<Class:Marshal>", "dump", -1, ""),
    (
        "#<Class:Marshal>",
        "load",
        -2,
        "req:source,opt:proc,key:freeze",
    ),
    (
        "#<Class:Marshal>",
        "restore",
        -2,
        "req:source,opt:proc,key:freeze",
    ),
    ("#<Class:Math>", "acos", 1, ""),
    ("#<Class:Math>", "acosh", 1, ""),
    ("#<Class:Math>", "asin", 1, ""),
    ("#<Class:Math>", "asinh", 1, ""),
    ("#<Class:Math>", "atan", 1, ""),
    ("#<Class:Math>", "atan2", 2, ""),
    ("#<Class:Math>", "atanh", 1, ""),
    ("#<Class:Math>", "cbrt", 1, ""),
    ("#<Class:Math>", "cos", 1, ""),
    ("#<Class:Math>", "cosh", 1, ""),
    ("#<Class:Math>", "erf", 1, ""),
    ("#<Class:Math>", "erfc", 1, ""),
    ("#<Class:Math>", "exp", 1, ""),
    ("#<Class:Math>", "expm1", 1, ""),
    ("#<Class:Math>", "frexp", 1, ""),
    ("#<Class:Math>", "gamma", 1, ""),
    ("#<Class:Math>", "hypot", 2, ""),
    ("#<Class:Math>", "ldexp", 2, ""),
    ("#<Class:Math>", "lgamma", 1, ""),
    ("#<Class:Math>", "log", -1, ""),
    ("#<Class:Math>", "log10", 1, ""),
    ("#<Class:Math>", "log1p", 1, ""),
    ("#<Class:Math>", "log2", 1, ""),
    ("#<Class:Math>", "sin", 1, ""),
    ("#<Class:Math>", "sinh", 1, ""),
    ("#<Class:Math>", "sqrt", 1, ""),
    ("#<Class:Math>", "tan", 1, ""),
    ("#<Class:Math>", "tanh", 1, ""),
    ("#<Class:Module>", "constants", -1, ""),
    ("#<Class:Module>", "nesting", 0, ""),
    ("#<Class:Module>", "used_modules", 0, ""),
    ("#<Class:Module>", "used_refinements", 0, ""),
    ("#<Class:ObjectSpace>", "_id2ref", 1, ""),
    ("#<Class:ObjectSpace>", "count_objects", -1, ""),
    ("#<Class:ObjectSpace>", "define_finalizer", -1, ""),
    ("#<Class:ObjectSpace>", "each_object", -1, ""),
    (
        "#<Class:ObjectSpace>",
        "garbage_collect",
        -1,
        "key:full_mark,key:immediate_mark,key:immediate_sweep",
    ),
    ("#<Class:ObjectSpace>", "undefine_finalizer", 1, ""),
    ("#<Class:Proc>", "new", -1, ""),
    ("#<Class:Process>", "_fork", 0, ""),
    ("#<Class:Process>", "abort", -1, ""),
    ("#<Class:Process>", "argv0", 0, ""),
    ("#<Class:Process>", "clock_getres", -1, ""),
    ("#<Class:Process>", "clock_gettime", -1, ""),
    ("#<Class:Process>", "daemon", -1, ""),
    ("#<Class:Process>", "detach", 1, ""),
    ("#<Class:Process>", "egid", 0, ""),
    ("#<Class:Process>", "egid=", 1, ""),
    ("#<Class:Process>", "euid", 0, ""),
    ("#<Class:Process>", "euid=", 1, ""),
    ("#<Class:Process>", "exec", -1, ""),
    ("#<Class:Process>", "exit", -1, ""),
    ("#<Class:Process>", "exit!", -1, ""),
    ("#<Class:Process>", "fork", 0, ""),
    ("#<Class:Process>", "getpgid", 1, ""),
    ("#<Class:Process>", "getpgrp", 0, ""),
    ("#<Class:Process>", "getpriority", 2, ""),
    ("#<Class:Process>", "getrlimit", 1, ""),
    ("#<Class:Process>", "getsid", -1, ""),
    ("#<Class:Process>", "gid", 0, ""),
    ("#<Class:Process>", "gid=", 1, ""),
    ("#<Class:Process>", "groups", 0, ""),
    ("#<Class:Process>", "groups=", 1, ""),
    ("#<Class:Process>", "initgroups", 2, ""),
    ("#<Class:Process>", "kill", -1, ""),
    ("#<Class:Process>", "last_status", 0, ""),
    ("#<Class:Process>", "maxgroups", 0, ""),
    ("#<Class:Process>", "maxgroups=", 1, ""),
    ("#<Class:Process>", "pid", 0, ""),
    ("#<Class:Process>", "ppid", 0, ""),
    ("#<Class:Process>", "setpgid", 2, ""),
    ("#<Class:Process>", "setpgrp", 0, ""),
    ("#<Class:Process>", "setpriority", 3, ""),
    ("#<Class:Process>", "setproctitle", 1, ""),
    ("#<Class:Process>", "setrlimit", -1, ""),
    ("#<Class:Process>", "setsid", 0, ""),
    ("#<Class:Process>", "spawn", -1, ""),
    ("#<Class:Process>", "times", 0, ""),
    ("#<Class:Process>", "uid", 0, ""),
    ("#<Class:Process>", "uid=", 1, ""),
    ("#<Class:Process>", "wait", -1, ""),
    ("#<Class:Process>", "wait2", -1, ""),
    ("#<Class:Process>", "waitall", 0, ""),
    ("#<Class:Process>", "waitpid", -1, ""),
    ("#<Class:Process>", "waitpid2", -1, ""),
    ("#<Class:Process>", "warmup", 0, ""),
    ("#<Class:Random>", "bytes", 1, ""),
    ("#<Class:Random>", "new_seed", 0, ""),
    ("#<Class:Random>", "rand", -1, ""),
    ("#<Class:Random>", "seed", 0, ""),
    ("#<Class:Random>", "srand", -1, ""),
    ("#<Class:Random>", "urandom", 1, ""),
    ("#<Class:Regexp>", "compile", -1, ""),
    ("#<Class:Regexp>", "escape", 1, ""),
    ("#<Class:Regexp>", "last_match", -1, ""),
    ("#<Class:Regexp>", "linear_time?", -1, ""),
    ("#<Class:Regexp>", "quote", 1, ""),
    ("#<Class:Regexp>", "timeout", 0, ""),
    ("#<Class:Regexp>", "timeout=", 1, ""),
    ("#<Class:Regexp>", "try_convert", 1, ""),
    ("#<Class:Regexp>", "union", -1, ""),
    ("#<Class:Set>", "[]", -1, ""),
    ("#<Class:Signal>", "list", 0, ""),
    ("#<Class:Signal>", "signame", 1, ""),
    ("#<Class:Signal>", "trap", -1, ""),
    ("#<Class:String>", "new", -1, ""),
    ("#<Class:String>", "try_convert", 1, ""),
    ("#<Class:Struct>", "new", -1, ""),
    ("#<Class:Symbol>", "all_symbols", 0, ""),
    ("#<Class:Thread>", "abort_on_exception", 0, ""),
    ("#<Class:Thread>", "abort_on_exception=", 1, ""),
    ("#<Class:Thread>", "current", 0, ""),
    ("#<Class:Thread>", "each_caller_location", -1, ""),
    ("#<Class:Thread>", "exit", 0, ""),
    ("#<Class:Thread>", "fork", -1, ""),
    ("#<Class:Thread>", "handle_interrupt", 1, ""),
    ("#<Class:Thread>", "ignore_deadlock", 0, ""),
    ("#<Class:Thread>", "ignore_deadlock=", 1, ""),
    ("#<Class:Thread>", "kill", 1, ""),
    ("#<Class:Thread>", "list", 0, ""),
    ("#<Class:Thread>", "main", 0, ""),
    ("#<Class:Thread>", "new", -1, ""),
    ("#<Class:Thread>", "pass", 0, ""),
    ("#<Class:Thread>", "pending_interrupt?", -1, ""),
    ("#<Class:Thread>", "report_on_exception", 0, ""),
    ("#<Class:Thread>", "report_on_exception=", 1, ""),
    ("#<Class:Thread>", "start", -1, ""),
    ("#<Class:Thread>", "stop", 0, ""),
    (
        "#<Class:Time>",
        "at",
        -2,
        "req:time,opt:subsec,opt:unit,key:in",
    ),
    ("#<Class:Time>", "gm", -1, ""),
    ("#<Class:Time>", "local", -1, ""),
    ("#<Class:Time>", "mktime", -1, ""),
    ("#<Class:Time>", "now", -1, "key:in"),
    ("#<Class:Time>", "utc", -1, ""),
    ("#<Class:Warning>", "[]", 1, ""),
    ("#<Class:Warning>", "[]=", 2, ""),
    ("#<Class:Warning>", "categories", 0, ""),
    ("Array", "&", 1, ""),
    ("Array", "*", 1, ""),
    ("Array", "+", 1, ""),
    ("Array", "-", 1, ""),
    ("Array", "<<", 1, ""),
    ("Array", "<=>", 1, ""),
    ("Array", "==", 1, ""),
    ("Array", "[]", -1, ""),
    ("Array", "[]=", -1, ""),
    ("Array", "all?", -1, ""),
    ("Array", "any?", -1, ""),
    ("Array", "append", -1, ""),
    ("Array", "assoc", 1, ""),
    ("Array", "at", 1, ""),
    ("Array", "bsearch", 0, ""),
    ("Array", "bsearch_index", 0, ""),
    ("Array", "clear", 0, ""),
    ("Array", "collect", 0, ""),
    ("Array", "collect!", 0, ""),
    ("Array", "combination", 1, ""),
    ("Array", "compact", 0, ""),
    ("Array", "compact!", 0, ""),
    ("Array", "concat", -1, ""),
    ("Array", "count", -1, ""),
    ("Array", "cycle", -1, ""),
    ("Array", "deconstruct", 0, ""),
    ("Array", "delete", 1, ""),
    ("Array", "delete_at", 1, ""),
    ("Array", "delete_if", 0, ""),
    ("Array", "detect", -1, ""),
    ("Array", "difference", -1, ""),
    ("Array", "dig", -1, ""),
    ("Array", "drop", 1, ""),
    ("Array", "drop_while", 0, ""),
    ("Array", "each", 0, ""),
    ("Array", "each_index", 0, ""),
    ("Array", "empty?", 0, ""),
    ("Array", "eql?", 1, ""),
    ("Array", "fetch", -1, ""),
    ("Array", "fetch_values", -1, "rest:indexes,block:block"),
    ("Array", "fill", -1, ""),
    ("Array", "filter", 0, ""),
    ("Array", "filter!", 0, ""),
    ("Array", "find", -1, ""),
    ("Array", "find_index", -1, ""),
    ("Array", "first", -1, "opt:n"),
    ("Array", "flatten", -1, ""),
    ("Array", "flatten!", -1, ""),
    ("Array", "freeze", 0, ""),
    ("Array", "hash", 0, ""),
    ("Array", "include?", 1, ""),
    ("Array", "index", -1, ""),
    ("Array", "initialize", -1, ""),
    ("Array", "initialize_copy", 1, ""),
    ("Array", "insert", -1, ""),
    ("Array", "inspect", 0, ""),
    ("Array", "intersect?", 1, ""),
    ("Array", "intersection", -1, ""),
    ("Array", "join", -1, ""),
    ("Array", "keep_if", 0, ""),
    ("Array", "last", -1, "opt:n"),
    ("Array", "length", 0, ""),
    ("Array", "map", 0, ""),
    ("Array", "map!", 0, ""),
    ("Array", "max", -1, ""),
    ("Array", "min", -1, ""),
    ("Array", "minmax", 0, ""),
    ("Array", "none?", -1, ""),
    ("Array", "one?", -1, ""),
    ("Array", "pack", -2, "req:fmt,key:buffer"),
    ("Array", "permutation", -1, ""),
    ("Array", "pop", -1, ""),
    ("Array", "prepend", -1, ""),
    ("Array", "product", -1, ""),
    ("Array", "push", -1, ""),
    ("Array", "rassoc", 1, ""),
    ("Array", "reject", 0, ""),
    ("Array", "reject!", 0, ""),
    ("Array", "repeated_combination", 1, ""),
    ("Array", "repeated_permutation", 1, ""),
    ("Array", "replace", 1, ""),
    ("Array", "reverse", 0, ""),
    ("Array", "reverse!", 0, ""),
    ("Array", "reverse_each", 0, ""),
    ("Array", "rfind", -1, ""),
    ("Array", "rindex", -1, ""),
    ("Array", "rotate", -1, ""),
    ("Array", "rotate!", -1, ""),
    ("Array", "sample", -1, "opt:n,key:random"),
    ("Array", "select", 0, ""),
    ("Array", "select!", 0, ""),
    ("Array", "shift", -1, ""),
    ("Array", "shuffle", -1, "key:random"),
    ("Array", "shuffle!", -1, "key:random"),
    ("Array", "size", 0, ""),
    ("Array", "slice", -1, ""),
    ("Array", "slice!", -1, ""),
    ("Array", "sort", 0, ""),
    ("Array", "sort!", 0, ""),
    ("Array", "sort_by!", 0, ""),
    ("Array", "sum", -1, ""),
    ("Array", "take", 1, ""),
    ("Array", "take_while", 0, ""),
    ("Array", "to_a", 0, ""),
    ("Array", "to_ary", 0, ""),
    ("Array", "to_h", 0, ""),
    ("Array", "to_s", 0, ""),
    ("Array", "transpose", 0, ""),
    ("Array", "union", -1, ""),
    ("Array", "uniq", 0, ""),
    ("Array", "uniq!", 0, ""),
    ("Array", "unshift", -1, ""),
    ("Array", "values_at", -1, ""),
    ("Array", "zip", -1, ""),
    ("Array", "|", 1, ""),
    ("BasicObject", "!", 0, ""),
    ("BasicObject", "!=", 1, ""),
    ("BasicObject", "==", 1, ""),
    ("BasicObject", "__id__", 0, ""),
    ("BasicObject", "__send__", -1, ""),
    ("BasicObject", "equal?", 1, ""),
    ("BasicObject", "initialize", 0, ""),
    ("BasicObject", "instance_eval", -1, ""),
    ("BasicObject", "instance_exec", -1, ""),
    ("BasicObject", "method_missing", -1, ""),
    ("BasicObject", "singleton_method_added", 1, ""),
    ("BasicObject", "singleton_method_removed", 1, ""),
    ("BasicObject", "singleton_method_undefined", 1, ""),
    ("Binding", "clone", 0, ""),
    ("Binding", "dup", 0, ""),
    ("Binding", "eval", -1, ""),
    ("Binding", "implicit_parameter_defined?", 1, ""),
    ("Binding", "implicit_parameter_get", 1, ""),
    ("Binding", "implicit_parameters", 0, ""),
    ("Binding", "irb", -1, "rest:*,keyrest:**,block:&"),
    ("Binding", "local_variable_defined?", 1, ""),
    ("Binding", "local_variable_get", 1, ""),
    ("Binding", "local_variable_set", 2, ""),
    ("Binding", "local_variables", 0, ""),
    ("Binding", "receiver", 0, ""),
    ("Binding", "source_location", 0, ""),
    ("Class", "allocate", 0, ""),
    ("Class", "attached_object", 0, ""),
    ("Class", "inherited", 1, ""),
    ("Class", "initialize", -1, ""),
    ("Class", "new", -1, ""),
    ("Class", "subclasses", 0, ""),
    ("Class", "superclass", 0, ""),
    ("Comparable", "<", 1, ""),
    ("Comparable", "<=", 1, ""),
    ("Comparable", "==", 1, ""),
    ("Comparable", ">", 1, ""),
    ("Comparable", ">=", 1, ""),
    ("Comparable", "between?", 2, ""),
    ("Comparable", "clamp", -1, ""),
    ("Complex", "*", 1, ""),
    ("Complex", "**", 1, ""),
    ("Complex", "+", 1, ""),
    ("Complex", "-", 1, ""),
    ("Complex", "-@", 0, ""),
    ("Complex", "/", 1, ""),
    ("Complex", "<=>", 1, ""),
    ("Complex", "==", 1, ""),
    ("Complex", "abs", 0, ""),
    ("Complex", "abs2", 0, ""),
    ("Complex", "angle", 0, ""),
    ("Complex", "arg", 0, ""),
    ("Complex", "coerce", 1, ""),
    ("Complex", "conj", 0, ""),
    ("Complex", "conjugate", 0, ""),
    ("Complex", "denominator", 0, ""),
    ("Complex", "eql?", 1, ""),
    ("Complex", "fdiv", 1, ""),
    ("Complex", "finite?", 0, ""),
    ("Complex", "hash", 0, ""),
    ("Complex", "imag", 0, ""),
    ("Complex", "imaginary", 0, ""),
    ("Complex", "infinite?", 0, ""),
    ("Complex", "inspect", 0, ""),
    ("Complex", "magnitude", 0, ""),
    ("Complex", "marshal_dump", 0, ""),
    ("Complex", "numerator", 0, ""),
    ("Complex", "phase", 0, ""),
    ("Complex", "polar", 0, ""),
    ("Complex", "quo", 1, ""),
    ("Complex", "rationalize", -1, ""),
    ("Complex", "real", 0, ""),
    ("Complex", "real?", 0, ""),
    ("Complex", "rect", 0, ""),
    ("Complex", "rectangular", 0, ""),
    ("Complex", "to_c", 0, ""),
    ("Complex", "to_f", 0, ""),
    ("Complex", "to_i", 0, ""),
    ("Complex", "to_r", 0, ""),
    ("Complex", "to_s", 0, ""),
    ("Data", "==", 1, ""),
    ("Data", "deconstruct", 0, ""),
    ("Data", "deconstruct_keys", 1, ""),
    ("Data", "eql?", 1, ""),
    ("Data", "hash", 0, ""),
    ("Data", "initialize", -1, ""),
    ("Data", "initialize_copy", 1, ""),
    ("Data", "inspect", 0, ""),
    ("Data", "members", 0, ""),
    ("Data", "to_h", 0, ""),
    ("Data", "to_s", 0, ""),
    ("Data", "with", -1, ""),
    ("Dir", "chdir", 0, ""),
    ("Dir", "children", 0, ""),
    ("Dir", "close", 0, ""),
    ("Dir", "each", 0, ""),
    ("Dir", "each_child", 0, ""),
    ("Dir", "fileno", 0, ""),
    ("Dir", "initialize", -2, "req:name,key:encoding"),
    ("Dir", "inspect", 0, ""),
    ("Dir", "path", 0, ""),
    ("Dir", "pos", 0, ""),
    ("Dir", "pos=", 1, ""),
    ("Dir", "read", 0, ""),
    ("Dir", "rewind", 0, ""),
    ("Dir", "seek", 1, ""),
    ("Dir", "tell", 0, ""),
    ("Dir", "to_path", 0, ""),
    ("Encoding", "_dump", -1, ""),
    ("Encoding", "ascii_compatible?", 0, ""),
    ("Encoding", "dummy?", 0, ""),
    ("Encoding", "inspect", 0, ""),
    ("Encoding", "name", 0, ""),
    ("Encoding", "names", 0, ""),
    ("Encoding", "to_s", 0, ""),
    ("Enumerable", "all?", -1, ""),
    ("Enumerable", "any?", -1, ""),
    ("Enumerable", "chain", -1, ""),
    ("Enumerable", "chunk", 0, ""),
    ("Enumerable", "chunk_while", 0, ""),
    ("Enumerable", "collect", 0, ""),
    ("Enumerable", "collect_concat", 0, ""),
    ("Enumerable", "compact", 0, ""),
    ("Enumerable", "count", -1, ""),
    ("Enumerable", "cycle", -1, ""),
    ("Enumerable", "detect", -1, ""),
    ("Enumerable", "drop", 1, ""),
    ("Enumerable", "drop_while", 0, ""),
    ("Enumerable", "each_cons", 1, ""),
    ("Enumerable", "each_entry", -1, ""),
    ("Enumerable", "each_slice", 1, ""),
    ("Enumerable", "each_with_index", -1, ""),
    ("Enumerable", "each_with_object", 1, ""),
    ("Enumerable", "entries", -1, ""),
    ("Enumerable", "filter", 0, ""),
    ("Enumerable", "filter_map", 0, ""),
    ("Enumerable", "find", -1, ""),
    ("Enumerable", "find_all", 0, ""),
    ("Enumerable", "find_index", -1, ""),
    ("Enumerable", "first", -1, ""),
    ("Enumerable", "flat_map", 0, ""),
    ("Enumerable", "grep", 1, ""),
    ("Enumerable", "grep_v", 1, ""),
    ("Enumerable", "group_by", 0, ""),
    ("Enumerable", "include?", 1, ""),
    ("Enumerable", "inject", -1, ""),
    ("Enumerable", "lazy", 0, ""),
    ("Enumerable", "map", 0, ""),
    ("Enumerable", "max", -1, ""),
    ("Enumerable", "max_by", -1, ""),
    ("Enumerable", "member?", 1, ""),
    ("Enumerable", "min", -1, ""),
    ("Enumerable", "min_by", -1, ""),
    ("Enumerable", "minmax", 0, ""),
    ("Enumerable", "minmax_by", 0, ""),
    ("Enumerable", "none?", -1, ""),
    ("Enumerable", "one?", -1, ""),
    ("Enumerable", "partition", 0, ""),
    ("Enumerable", "reduce", -1, ""),
    ("Enumerable", "reject", 0, ""),
    ("Enumerable", "reverse_each", -1, ""),
    ("Enumerable", "select", 0, ""),
    ("Enumerable", "slice_after", -1, ""),
    ("Enumerable", "slice_before", -1, ""),
    ("Enumerable", "slice_when", 0, ""),
    ("Enumerable", "sort", 0, ""),
    ("Enumerable", "sort_by", 0, ""),
    ("Enumerable", "sum", -1, ""),
    ("Enumerable", "take", 1, ""),
    ("Enumerable", "take_while", 0, ""),
    ("Enumerable", "tally", -1, ""),
    ("Enumerable", "to_a", -1, ""),
    ("Enumerable", "to_h", -1, ""),
    ("Enumerable", "to_set", -1, "rest:args,block:block"),
    ("Enumerable", "uniq", 0, ""),
    ("Enumerable", "zip", -1, ""),
    ("Enumerator", "+", 1, ""),
    ("Enumerator", "each", -1, ""),
    ("Enumerator", "each_with_index", 0, ""),
    ("Enumerator", "each_with_object", 1, ""),
    ("Enumerator", "feed", 1, ""),
    ("Enumerator", "initialize", -1, ""),
    ("Enumerator", "initialize_copy", 1, ""),
    ("Enumerator", "inspect", 0, ""),
    ("Enumerator", "next", 0, ""),
    ("Enumerator", "next_values", 0, ""),
    ("Enumerator", "peek", 0, ""),
    ("Enumerator", "peek_values", 0, ""),
    ("Enumerator", "rewind", 0, ""),
    ("Enumerator", "size", 0, ""),
    ("Enumerator", "with_index", -1, ""),
    ("Enumerator", "with_object", 1, ""),
    ("Enumerator::Lazy", "_enumerable_collect", 0, ""),
    ("Enumerator::Lazy", "_enumerable_collect_concat", 0, ""),
    ("Enumerator::Lazy", "_enumerable_drop", 1, ""),
    ("Enumerator::Lazy", "_enumerable_drop_while", 0, ""),
    ("Enumerator::Lazy", "_enumerable_filter", 0, ""),
    ("Enumerator::Lazy", "_enumerable_filter_map", 0, ""),
    ("Enumerator::Lazy", "_enumerable_find_all", 0, ""),
    ("Enumerator::Lazy", "_enumerable_flat_map", 0, ""),
    ("Enumerator::Lazy", "_enumerable_grep", 1, ""),
    ("Enumerator::Lazy", "_enumerable_grep_v", 1, ""),
    ("Enumerator::Lazy", "_enumerable_map", 0, ""),
    ("Enumerator::Lazy", "_enumerable_reject", 0, ""),
    ("Enumerator::Lazy", "_enumerable_select", 0, ""),
    ("Enumerator::Lazy", "_enumerable_take", 1, ""),
    ("Enumerator::Lazy", "_enumerable_take_while", 0, ""),
    ("Enumerator::Lazy", "_enumerable_uniq", 0, ""),
    ("Enumerator::Lazy", "_enumerable_with_index", -1, ""),
    ("Enumerator::Lazy", "_enumerable_zip", -1, ""),
    ("Enumerator::Lazy", "chunk", -1, ""),
    ("Enumerator::Lazy", "chunk_while", -1, ""),
    ("Enumerator::Lazy", "collect", 0, ""),
    ("Enumerator::Lazy", "collect_concat", 0, ""),
    ("Enumerator::Lazy", "compact", 0, ""),
    ("Enumerator::Lazy", "drop", 1, ""),
    ("Enumerator::Lazy", "drop_while", 0, ""),
    ("Enumerator::Lazy", "eager", 0, ""),
    ("Enumerator::Lazy", "enum_for", -1, ""),
    ("Enumerator::Lazy", "filter", 0, ""),
    ("Enumerator::Lazy", "filter_map", 0, ""),
    ("Enumerator::Lazy", "find_all", 0, ""),
    ("Enumerator::Lazy", "flat_map", 0, ""),
    ("Enumerator::Lazy", "force", -1, ""),
    ("Enumerator::Lazy", "grep", 1, ""),
    ("Enumerator::Lazy", "grep_v", 1, ""),
    ("Enumerator::Lazy", "initialize", -1, ""),
    ("Enumerator::Lazy", "lazy", 0, ""),
    ("Enumerator::Lazy", "map", 0, ""),
    ("Enumerator::Lazy", "reject", 0, ""),
    ("Enumerator::Lazy", "select", 0, ""),
    ("Enumerator::Lazy", "slice_after", -1, ""),
    ("Enumerator::Lazy", "slice_before", -1, ""),
    ("Enumerator::Lazy", "slice_when", -1, ""),
    ("Enumerator::Lazy", "take", 1, ""),
    ("Enumerator::Lazy", "take_while", 0, ""),
    ("Enumerator::Lazy", "to_enum", -1, ""),
    ("Enumerator::Lazy", "uniq", 0, ""),
    ("Enumerator::Lazy", "with_index", -1, ""),
    ("Enumerator::Lazy", "zip", -1, ""),
    ("Enumerator::Yielder", "<<", 1, ""),
    ("Enumerator::Yielder", "initialize", 0, ""),
    ("Enumerator::Yielder", "to_proc", 0, ""),
    ("Enumerator::Yielder", "yield", -1, ""),
    ("Exception", "==", 1, ""),
    ("Exception", "backtrace", 0, ""),
    ("Exception", "backtrace_locations", 0, ""),
    ("Exception", "cause", 0, ""),
    ("Exception", "detailed_message", -1, ""),
    ("Exception", "exception", -1, ""),
    ("Exception", "full_message", -1, ""),
    ("Exception", "initialize", -1, ""),
    ("Exception", "inspect", 0, ""),
    ("Exception", "message", 0, ""),
    ("Exception", "method_missing", -1, ""),
    ("Exception", "respond_to?", -1, ""),
    ("Exception", "respond_to_missing?", 2, ""),
    ("Exception", "set_backtrace", 1, ""),
    ("Exception", "to_s", 0, ""),
    ("FalseClass", "&", 1, ""),
    ("FalseClass", "===", 1, ""),
    ("FalseClass", "^", 1, ""),
    ("FalseClass", "inspect", 0, ""),
    ("FalseClass", "to_s", 0, ""),
    ("FalseClass", "|", 1, ""),
    ("Fiber", "alive?", 0, ""),
    ("Fiber", "backtrace", -1, ""),
    ("Fiber", "backtrace_locations", -1, ""),
    ("Fiber", "blocking?", 0, ""),
    ("Fiber", "initialize", -1, ""),
    ("Fiber", "inspect", 0, ""),
    ("Fiber", "kill", 0, ""),
    ("Fiber", "raise", -1, ""),
    ("Fiber", "resume", -1, ""),
    ("Fiber", "storage", 0, ""),
    ("Fiber", "storage=", 1, ""),
    ("Fiber", "to_s", 0, ""),
    ("Fiber", "transfer", -1, ""),
    ("File", "atime", 0, ""),
    ("File", "birthtime", 0, ""),
    ("File", "chmod", 1, ""),
    ("File", "chown", 2, ""),
    ("File", "ctime", 0, ""),
    ("File", "flock", 1, ""),
    ("File", "initialize", -1, ""),
    ("File", "lstat", 0, ""),
    ("File", "mtime", 0, ""),
    ("File", "size", 0, ""),
    ("File", "truncate", 1, ""),
    ("FileTest", "blockdev?", 1, ""),
    ("FileTest", "chardev?", 1, ""),
    ("FileTest", "directory?", 1, ""),
    ("FileTest", "empty?", 1, ""),
    ("FileTest", "executable?", 1, ""),
    ("FileTest", "executable_real?", 1, ""),
    ("FileTest", "exist?", 1, ""),
    ("FileTest", "file?", 1, ""),
    ("FileTest", "grpowned?", 1, ""),
    ("FileTest", "identical?", 2, ""),
    ("FileTest", "owned?", 1, ""),
    ("FileTest", "pipe?", 1, ""),
    ("FileTest", "readable?", 1, ""),
    ("FileTest", "readable_real?", 1, ""),
    ("FileTest", "setgid?", 1, ""),
    ("FileTest", "setuid?", 1, ""),
    ("FileTest", "size", 1, ""),
    ("FileTest", "size?", 1, ""),
    ("FileTest", "socket?", 1, ""),
    ("FileTest", "sticky?", 1, ""),
    ("FileTest", "symlink?", 1, ""),
    ("FileTest", "world_readable?", 1, ""),
    ("FileTest", "world_writable?", 1, ""),
    ("FileTest", "writable?", 1, ""),
    ("FileTest", "writable_real?", 1, ""),
    ("FileTest", "zero?", 1, ""),
    ("Float", "%", 1, ""),
    ("Float", "*", 1, ""),
    ("Float", "**", 1, ""),
    ("Float", "+", 1, ""),
    ("Float", "-", 1, ""),
    ("Float", "-@", 0, ""),
    ("Float", "/", 1, ""),
    ("Float", "<", 1, ""),
    ("Float", "<=", 1, ""),
    ("Float", "<=>", 1, ""),
    ("Float", "==", 1, ""),
    ("Float", "===", 1, ""),
    ("Float", ">", 1, ""),
    ("Float", ">=", 1, ""),
    ("Float", "abs", 0, ""),
    ("Float", "angle", 0, ""),
    ("Float", "arg", 0, ""),
    ("Float", "ceil", -1, ""),
    ("Float", "coerce", 1, ""),
    ("Float", "denominator", 0, ""),
    ("Float", "divmod", 1, ""),
    ("Float", "eql?", 1, ""),
    ("Float", "fdiv", 1, ""),
    ("Float", "finite?", 0, ""),
    ("Float", "floor", -1, ""),
    ("Float", "hash", 0, ""),
    ("Float", "infinite?", 0, ""),
    ("Float", "inspect", 0, ""),
    ("Float", "magnitude", 0, ""),
    ("Float", "modulo", 1, ""),
    ("Float", "nan?", 0, ""),
    ("Float", "negative?", 0, ""),
    ("Float", "next_float", 0, ""),
    ("Float", "numerator", 0, ""),
    ("Float", "phase", 0, ""),
    ("Float", "positive?", 0, ""),
    ("Float", "prev_float", 0, ""),
    ("Float", "quo", 1, ""),
    ("Float", "rationalize", -1, ""),
    ("Float", "round", -1, ""),
    ("Float", "to_f", 0, ""),
    ("Float", "to_i", 0, ""),
    ("Float", "to_int", 0, ""),
    ("Float", "to_r", 0, ""),
    ("Float", "to_s", 0, ""),
    ("Float", "truncate", -1, ""),
    ("Float", "zero?", 0, ""),
    ("FrozenError", "initialize", -1, ""),
    ("FrozenError", "receiver", 0, ""),
    (
        "GC",
        "garbage_collect",
        -1,
        "key:full_mark,key:immediate_mark,key:immediate_sweep",
    ),
    ("Hash", "<", 1, ""),
    ("Hash", "<=", 1, ""),
    ("Hash", "==", 1, ""),
    ("Hash", ">", 1, ""),
    ("Hash", ">=", 1, ""),
    ("Hash", "[]", 1, ""),
    ("Hash", "[]=", 2, ""),
    ("Hash", "any?", -1, ""),
    ("Hash", "assoc", 1, ""),
    ("Hash", "clear", 0, ""),
    ("Hash", "compact", 0, ""),
    ("Hash", "compact!", 0, ""),
    ("Hash", "compare_by_identity", 0, ""),
    ("Hash", "compare_by_identity?", 0, ""),
    ("Hash", "deconstruct_keys", 1, ""),
    ("Hash", "default", -1, ""),
    ("Hash", "default=", 1, ""),
    ("Hash", "default_proc", 0, ""),
    ("Hash", "default_proc=", 1, ""),
    ("Hash", "delete", 1, ""),
    ("Hash", "delete_if", 0, ""),
    ("Hash", "dig", -1, ""),
    ("Hash", "each", 0, ""),
    ("Hash", "each_key", 0, ""),
    ("Hash", "each_pair", 0, ""),
    ("Hash", "each_value", 0, ""),
    ("Hash", "empty?", 0, ""),
    ("Hash", "eql?", 1, ""),
    ("Hash", "except", -1, ""),
    ("Hash", "fetch", -1, ""),
    ("Hash", "fetch_values", -1, ""),
    ("Hash", "filter", 0, ""),
    ("Hash", "filter!", 0, ""),
    ("Hash", "flatten", -1, ""),
    ("Hash", "freeze", 0, ""),
    ("Hash", "has_key?", 1, ""),
    ("Hash", "has_value?", 1, ""),
    ("Hash", "hash", 0, ""),
    ("Hash", "include?", 1, ""),
    (
        "Hash",
        "initialize",
        -1,
        "opt:ifnone,key:capacity,block:block",
    ),
    ("Hash", "initialize_copy", 1, ""),
    ("Hash", "inspect", 0, ""),
    ("Hash", "invert", 0, ""),
    ("Hash", "keep_if", 0, ""),
    ("Hash", "key", 1, ""),
    ("Hash", "key?", 1, ""),
    ("Hash", "keys", 0, ""),
    ("Hash", "length", 0, ""),
    ("Hash", "member?", 1, ""),
    ("Hash", "merge", -1, ""),
    ("Hash", "merge!", -1, ""),
    ("Hash", "rassoc", 1, ""),
    ("Hash", "rehash", 0, ""),
    ("Hash", "reject", 0, ""),
    ("Hash", "reject!", 0, ""),
    ("Hash", "replace", 1, ""),
    ("Hash", "select", 0, ""),
    ("Hash", "select!", 0, ""),
    ("Hash", "shift", 0, ""),
    ("Hash", "size", 0, ""),
    ("Hash", "slice", -1, ""),
    ("Hash", "store", 2, ""),
    ("Hash", "to_a", 0, ""),
    ("Hash", "to_h", 0, ""),
    ("Hash", "to_hash", 0, ""),
    ("Hash", "to_proc", 0, ""),
    ("Hash", "to_s", 0, ""),
    ("Hash", "transform_keys", -1, ""),
    ("Hash", "transform_keys!", -1, ""),
    ("Hash", "transform_values", 0, ""),
    ("Hash", "transform_values!", 0, ""),
    ("Hash", "update", -1, ""),
    ("Hash", "value?", 1, ""),
    ("Hash", "values", 0, ""),
    ("Hash", "values_at", -1, ""),
    ("IO", "<<", 1, ""),
    ("IO", "advise", -1, ""),
    ("IO", "autoclose=", 1, ""),
    ("IO", "autoclose?", 0, ""),
    ("IO", "binmode", 0, ""),
    ("IO", "binmode?", 0, ""),
    ("IO", "close", 0, ""),
    ("IO", "close_on_exec=", 1, ""),
    ("IO", "close_on_exec?", 0, ""),
    ("IO", "close_read", 0, ""),
    ("IO", "close_write", 0, ""),
    ("IO", "closed?", 0, ""),
    ("IO", "each", -1, ""),
    ("IO", "each_byte", 0, ""),
    ("IO", "each_char", 0, ""),
    ("IO", "each_codepoint", 0, ""),
    ("IO", "each_line", -1, ""),
    ("IO", "eof", 0, ""),
    ("IO", "eof?", 0, ""),
    ("IO", "external_encoding", 0, ""),
    ("IO", "fcntl", -1, ""),
    ("IO", "fdatasync", 0, ""),
    ("IO", "fileno", 0, ""),
    ("IO", "flush", 0, ""),
    ("IO", "fsync", 0, ""),
    ("IO", "getbyte", 0, ""),
    ("IO", "getc", 0, ""),
    ("IO", "gets", -1, ""),
    ("IO", "initialize", -1, ""),
    ("IO", "initialize_copy", 1, ""),
    ("IO", "inspect", 0, ""),
    ("IO", "internal_encoding", 0, ""),
    ("IO", "ioctl", -1, ""),
    ("IO", "isatty", 0, ""),
    ("IO", "lineno", 0, ""),
    ("IO", "lineno=", 1, ""),
    ("IO", "path", 0, ""),
    ("IO", "pid", 0, ""),
    ("IO", "pos", 0, ""),
    ("IO", "pos=", 1, ""),
    ("IO", "pread", -1, ""),
    ("IO", "print", -1, ""),
    ("IO", "printf", -1, ""),
    ("IO", "putc", 1, ""),
    ("IO", "puts", -1, ""),
    ("IO", "pwrite", 2, ""),
    ("IO", "read", -1, ""),
    ("IO", "read_nonblock", -2, "req:len,opt:buf,key:exception"),
    ("IO", "readbyte", 0, ""),
    ("IO", "readchar", 0, ""),
    ("IO", "readline", -1, "opt:sep,opt:limit,key:chomp"),
    ("IO", "readlines", -1, ""),
    ("IO", "readpartial", -1, ""),
    ("IO", "reopen", -1, ""),
    ("IO", "rewind", 0, ""),
    ("IO", "seek", -1, ""),
    ("IO", "set_encoding", -1, ""),
    ("IO", "set_encoding_by_bom", 0, ""),
    ("IO", "stat", 0, ""),
    ("IO", "sync", 0, ""),
    ("IO", "sync=", 1, ""),
    ("IO", "sysread", -1, ""),
    ("IO", "sysseek", -1, ""),
    ("IO", "syswrite", 1, ""),
    ("IO", "tell", 0, ""),
    ("IO", "timeout", 0, ""),
    ("IO", "timeout=", 1, ""),
    ("IO", "to_i", 0, ""),
    ("IO", "to_io", 0, ""),
    ("IO", "to_path", 0, ""),
    ("IO", "tty?", 0, ""),
    ("IO", "ungetbyte", 1, ""),
    ("IO", "ungetc", 1, ""),
    ("IO", "wait", -1, ""),
    ("IO", "wait_priority", -1, ""),
    ("IO", "wait_readable", -1, ""),
    ("IO", "wait_writable", -1, ""),
    ("IO", "write", -1, ""),
    ("IO", "write_nonblock", -2, "req:buf,key:exception"),
    ("Integer", "%", 1, ""),
    ("Integer", "&", 1, ""),
    ("Integer", "*", 1, ""),
    ("Integer", "**", 1, ""),
    ("Integer", "+", 1, ""),
    ("Integer", "-", 1, ""),
    ("Integer", "-@", 0, ""),
    ("Integer", "/", 1, ""),
    ("Integer", "<", 1, ""),
    ("Integer", "<<", 1, ""),
    ("Integer", "<=", 1, ""),
    ("Integer", "<=>", 1, ""),
    ("Integer", "==", 1, ""),
    ("Integer", "===", 1, ""),
    ("Integer", ">", 1, ""),
    ("Integer", ">=", 1, ""),
    ("Integer", ">>", 1, ""),
    ("Integer", "[]", -1, ""),
    ("Integer", "^", 1, ""),
    ("Integer", "abs", 0, ""),
    ("Integer", "allbits?", 1, ""),
    ("Integer", "anybits?", 1, ""),
    ("Integer", "bit_length", 0, ""),
    ("Integer", "ceil", -1, ""),
    ("Integer", "ceildiv", 1, "req:other"),
    ("Integer", "chr", -1, ""),
    ("Integer", "coerce", 1, ""),
    ("Integer", "denominator", 0, ""),
    ("Integer", "digits", -1, ""),
    ("Integer", "div", 1, ""),
    ("Integer", "divmod", 1, ""),
    ("Integer", "downto", 1, ""),
    ("Integer", "even?", 0, ""),
    ("Integer", "fdiv", 1, ""),
    ("Integer", "floor", -1, ""),
    ("Integer", "gcd", 1, ""),
    ("Integer", "gcdlcm", 1, ""),
    ("Integer", "inspect", -1, ""),
    ("Integer", "integer?", 0, ""),
    ("Integer", "lcm", 1, ""),
    ("Integer", "magnitude", 0, ""),
    ("Integer", "modulo", 1, ""),
    ("Integer", "next", 0, ""),
    ("Integer", "nobits?", 1, ""),
    ("Integer", "numerator", 0, ""),
    ("Integer", "odd?", 0, ""),
    ("Integer", "ord", 0, ""),
    ("Integer", "pow", -1, ""),
    ("Integer", "pred", 0, ""),
    ("Integer", "rationalize", -1, ""),
    ("Integer", "remainder", 1, ""),
    ("Integer", "round", -1, ""),
    ("Integer", "size", 0, ""),
    ("Integer", "succ", 0, ""),
    ("Integer", "times", 0, ""),
    ("Integer", "to_f", 0, ""),
    ("Integer", "to_i", 0, ""),
    ("Integer", "to_int", 0, ""),
    ("Integer", "to_r", 0, ""),
    ("Integer", "to_s", -1, ""),
    ("Integer", "truncate", -1, ""),
    ("Integer", "upto", 1, ""),
    ("Integer", "zero?", 0, ""),
    ("Integer", "|", 1, ""),
    ("Integer", "~", 0, ""),
    ("Kernel", "!~", 1, ""),
    ("Kernel", "<=>", 1, ""),
    ("Kernel", "===", 1, ""),
    ("Kernel", "Array", 1, ""),
    ("Kernel", "Complex", -1, ""),
    ("Kernel", "Float", -2, "req:arg,key:exception"),
    ("Kernel", "Hash", 1, ""),
    ("Kernel", "Integer", -2, "req:arg,opt:base,key:exception"),
    ("Kernel", "Pathname", 1, "req:path"),
    ("Kernel", "Rational", -1, ""),
    ("Kernel", "String", 1, ""),
    ("Kernel", "__callee__", 0, ""),
    ("Kernel", "__dir__", 0, ""),
    ("Kernel", "__method__", 0, ""),
    ("Kernel", "`", 1, ""),
    ("Kernel", "abort", -1, ""),
    ("Kernel", "at_exit", 0, ""),
    ("Kernel", "autoload", 2, ""),
    ("Kernel", "autoload?", -1, ""),
    ("Kernel", "binding", 0, ""),
    ("Kernel", "block_given?", 0, ""),
    ("Kernel", "caller", -1, ""),
    ("Kernel", "caller_locations", -1, ""),
    ("Kernel", "catch", -1, ""),
    ("Kernel", "class", 0, ""),
    ("Kernel", "clone", -1, "key:freeze"),
    ("Kernel", "define_singleton_method", -1, ""),
    ("Kernel", "display", -1, ""),
    ("Kernel", "dup", 0, ""),
    ("Kernel", "enum_for", -1, ""),
    ("Kernel", "eql?", 1, ""),
    ("Kernel", "eval", -1, ""),
    ("Kernel", "exec", -1, ""),
    ("Kernel", "exit", -1, ""),
    ("Kernel", "exit!", -1, ""),
    ("Kernel", "extend", -1, ""),
    ("Kernel", "fail", -1, ""),
    ("Kernel", "fork", 0, ""),
    ("Kernel", "format", -1, ""),
    ("Kernel", "freeze", 0, ""),
    ("Kernel", "frozen?", 0, ""),
    ("Kernel", "gem", -2, "req:gem_name,rest:requirements"),
    ("Kernel", "gem_original_require", 1, ""),
    ("Kernel", "gets", -1, ""),
    ("Kernel", "global_variables", 0, ""),
    ("Kernel", "hash", 0, ""),
    ("Kernel", "initialize_clone", -1, ""),
    ("Kernel", "initialize_copy", 1, ""),
    ("Kernel", "initialize_dup", 1, ""),
    ("Kernel", "inspect", 0, ""),
    ("Kernel", "instance_of?", 1, ""),
    ("Kernel", "instance_variable_defined?", 1, ""),
    ("Kernel", "instance_variable_get", 1, ""),
    ("Kernel", "instance_variable_set", 2, ""),
    ("Kernel", "instance_variables", 0, ""),
    ("Kernel", "instance_variables_to_inspect", 0, ""),
    ("Kernel", "is_a?", 1, ""),
    ("Kernel", "iterator?", 0, ""),
    ("Kernel", "itself", 0, ""),
    ("Kernel", "kind_of?", 1, ""),
    ("Kernel", "lambda", 0, ""),
    ("Kernel", "load", -1, ""),
    ("Kernel", "local_variables", 0, ""),
    ("Kernel", "loop", 0, ""),
    ("Kernel", "method", 1, ""),
    ("Kernel", "methods", -1, ""),
    ("Kernel", "nil?", 0, ""),
    ("Kernel", "object_id", 0, ""),
    ("Kernel", "open", -1, ""),
    ("Kernel", "p", -1, ""),
    ("Kernel", "pp", -1, "rest:objs"),
    ("Kernel", "print", -1, ""),
    ("Kernel", "printf", -1, ""),
    ("Kernel", "private_methods", -1, ""),
    ("Kernel", "proc", 0, ""),
    ("Kernel", "protected_methods", -1, ""),
    ("Kernel", "public_method", 1, ""),
    ("Kernel", "public_methods", -1, ""),
    ("Kernel", "public_send", -1, ""),
    ("Kernel", "putc", 1, ""),
    ("Kernel", "puts", -1, ""),
    ("Kernel", "raise", -1, ""),
    ("Kernel", "rand", -1, ""),
    ("Kernel", "readline", -1, ""),
    ("Kernel", "readlines", -1, ""),
    ("Kernel", "remove_instance_variable", 1, ""),
    ("Kernel", "require", 1, "req:path"),
    ("Kernel", "require_relative", 1, ""),
    ("Kernel", "respond_to?", -1, ""),
    ("Kernel", "respond_to_missing?", 2, ""),
    ("Kernel", "select", -1, ""),
    ("Kernel", "send", -1, ""),
    ("Kernel", "set_trace_func", 1, ""),
    ("Kernel", "singleton_class", 0, ""),
    ("Kernel", "singleton_method", 1, ""),
    ("Kernel", "singleton_methods", -1, ""),
    ("Kernel", "sleep", -1, ""),
    ("Kernel", "spawn", -1, ""),
    ("Kernel", "sprintf", -1, ""),
    ("Kernel", "srand", -1, ""),
    ("Kernel", "syscall", 0, ""),
    ("Kernel", "system", -1, ""),
    ("Kernel", "tap", 0, ""),
    ("Kernel", "test", -1, ""),
    ("Kernel", "then", 0, ""),
    ("Kernel", "throw", -1, ""),
    ("Kernel", "to_enum", -1, ""),
    ("Kernel", "to_s", 0, ""),
    ("Kernel", "trace_var", -1, ""),
    ("Kernel", "trap", -1, ""),
    ("Kernel", "untrace_var", -1, ""),
    ("Kernel", "warn", -1, "rest:msgs,key:uplevel,key:category"),
    ("Kernel", "yield_self", 0, ""),
    ("KeyError", "initialize", -1, ""),
    ("KeyError", "key", 0, ""),
    ("KeyError", "receiver", 0, ""),
    ("LocalJumpError", "exit_value", 0, ""),
    ("LocalJumpError", "reason", 0, ""),
    ("Marshal", "dump", -1, ""),
    ("MatchData", "==", 1, ""),
    ("MatchData", "[]", -1, ""),
    ("MatchData", "begin", 1, ""),
    ("MatchData", "bytebegin", 1, ""),
    ("MatchData", "byteend", 1, ""),
    ("MatchData", "byteoffset", 1, ""),
    ("MatchData", "captures", 0, ""),
    ("MatchData", "deconstruct", 0, ""),
    ("MatchData", "deconstruct_keys", 1, ""),
    ("MatchData", "end", 1, ""),
    ("MatchData", "eql?", 1, ""),
    ("MatchData", "hash", 0, ""),
    ("MatchData", "initialize_copy", 1, ""),
    ("MatchData", "inspect", 0, ""),
    ("MatchData", "length", 0, ""),
    ("MatchData", "match", 1, ""),
    ("MatchData", "match_length", 1, ""),
    ("MatchData", "named_captures", -1, ""),
    ("MatchData", "names", 0, ""),
    ("MatchData", "offset", 1, ""),
    ("MatchData", "post_match", 0, ""),
    ("MatchData", "pre_match", 0, ""),
    ("MatchData", "regexp", 0, ""),
    ("MatchData", "size", 0, ""),
    ("MatchData", "string", 0, ""),
    ("MatchData", "to_a", 0, ""),
    ("MatchData", "to_s", 0, ""),
    ("MatchData", "values_at", -1, ""),
    ("Math", "acos", 1, ""),
    ("Math", "acosh", 1, ""),
    ("Math", "asin", 1, ""),
    ("Math", "asinh", 1, ""),
    ("Math", "atan", 1, ""),
    ("Math", "atan2", 2, ""),
    ("Math", "atanh", 1, ""),
    ("Math", "cbrt", 1, ""),
    ("Math", "cos", 1, ""),
    ("Math", "cosh", 1, ""),
    ("Math", "erf", 1, ""),
    ("Math", "erfc", 1, ""),
    ("Math", "exp", 1, ""),
    ("Math", "expm1", 1, ""),
    ("Math", "frexp", 1, ""),
    ("Math", "gamma", 1, ""),
    ("Math", "hypot", 2, ""),
    ("Math", "ldexp", 2, ""),
    ("Math", "lgamma", 1, ""),
    ("Math", "log", -1, ""),
    ("Math", "log10", 1, ""),
    ("Math", "log1p", 1, ""),
    ("Math", "log2", 1, ""),
    ("Math", "sin", 1, ""),
    ("Math", "sinh", 1, ""),
    ("Math", "sqrt", 1, ""),
    ("Math", "tan", 1, ""),
    ("Math", "tanh", 1, ""),
    ("Method", "<<", 1, ""),
    ("Method", "==", 1, ""),
    ("Method", "===", -1, ""),
    ("Method", ">>", 1, ""),
    ("Method", "[]", -1, ""),
    ("Method", "arity", 0, ""),
    ("Method", "box", 0, ""),
    ("Method", "call", -1, ""),
    ("Method", "clone", 0, ""),
    ("Method", "curry", -1, ""),
    ("Method", "dup", 0, ""),
    ("Method", "eql?", 1, ""),
    ("Method", "hash", 0, ""),
    ("Method", "inspect", 0, ""),
    ("Method", "name", 0, ""),
    ("Method", "original_name", 0, ""),
    ("Method", "owner", 0, ""),
    ("Method", "parameters", 0, ""),
    ("Method", "receiver", 0, ""),
    ("Method", "source_location", 0, ""),
    ("Method", "super_method", 0, ""),
    ("Method", "to_proc", 0, ""),
    ("Method", "to_s", 0, ""),
    ("Method", "unbind", 0, ""),
    ("Module", "<", 1, ""),
    ("Module", "<=", 1, ""),
    ("Module", "<=>", 1, ""),
    ("Module", "==", 1, ""),
    ("Module", "===", 1, ""),
    ("Module", ">", 1, ""),
    ("Module", ">=", 1, ""),
    ("Module", "alias_method", 2, ""),
    ("Module", "ancestors", 0, ""),
    ("Module", "append_features", 1, ""),
    ("Module", "attr", -1, ""),
    ("Module", "attr_accessor", -1, ""),
    ("Module", "attr_reader", -1, ""),
    ("Module", "attr_writer", -1, ""),
    ("Module", "autoload", 2, ""),
    ("Module", "autoload?", -1, ""),
    ("Module", "class_eval", -1, ""),
    ("Module", "class_exec", -1, ""),
    ("Module", "class_variable_defined?", 1, ""),
    ("Module", "class_variable_get", 1, ""),
    ("Module", "class_variable_set", 2, ""),
    ("Module", "class_variables", -1, ""),
    ("Module", "const_added", 1, ""),
    ("Module", "const_defined?", -1, ""),
    ("Module", "const_get", -1, ""),
    ("Module", "const_missing", 1, ""),
    ("Module", "const_set", 2, ""),
    ("Module", "const_source_location", -1, ""),
    ("Module", "constants", -1, ""),
    ("Module", "define_method", -1, ""),
    ("Module", "deprecate_constant", -1, ""),
    ("Module", "extend_object", 1, ""),
    ("Module", "extended", 1, ""),
    ("Module", "freeze", 0, ""),
    ("Module", "include", -1, ""),
    ("Module", "include?", 1, ""),
    ("Module", "included", 1, ""),
    ("Module", "included_modules", 0, ""),
    ("Module", "initialize", 0, ""),
    ("Module", "initialize_clone", -1, ""),
    ("Module", "inspect", 0, ""),
    ("Module", "instance_method", 1, ""),
    ("Module", "instance_methods", -1, ""),
    ("Module", "method_added", 1, ""),
    ("Module", "method_defined?", -1, ""),
    ("Module", "method_removed", 1, ""),
    ("Module", "method_undefined", 1, ""),
    ("Module", "module_eval", -1, ""),
    ("Module", "module_exec", -1, ""),
    ("Module", "module_function", -1, ""),
    ("Module", "name", 0, ""),
    ("Module", "prepend", -1, ""),
    ("Module", "prepend_features", 1, ""),
    ("Module", "prepended", 1, ""),
    ("Module", "private", -1, ""),
    ("Module", "private_class_method", -1, ""),
    ("Module", "private_constant", -1, ""),
    ("Module", "private_instance_methods", -1, ""),
    ("Module", "private_method_defined?", -1, ""),
    ("Module", "protected", -1, ""),
    ("Module", "protected_instance_methods", -1, ""),
    ("Module", "protected_method_defined?", -1, ""),
    ("Module", "public", -1, ""),
    ("Module", "public_class_method", -1, ""),
    ("Module", "public_constant", -1, ""),
    ("Module", "public_instance_method", 1, ""),
    ("Module", "public_instance_methods", -1, ""),
    ("Module", "public_method_defined?", -1, ""),
    ("Module", "refine", 1, ""),
    ("Module", "refinements", 0, ""),
    ("Module", "remove_class_variable", 1, ""),
    ("Module", "remove_const", 1, ""),
    ("Module", "remove_method", -1, ""),
    ("Module", "ruby2_keywords", -1, ""),
    ("Module", "set_temporary_name", 1, ""),
    ("Module", "singleton_class?", 0, ""),
    ("Module", "to_s", 0, ""),
    ("Module", "undef_method", -1, ""),
    ("Module", "undefined_instance_methods", 0, ""),
    ("Module", "using", 1, ""),
    ("NameError", "initialize", -1, ""),
    ("NameError", "local_variables", 0, ""),
    ("NameError", "name", 0, ""),
    ("NameError", "receiver", 0, ""),
    ("NilClass", "&", 1, ""),
    ("NilClass", "===", 1, ""),
    ("NilClass", "=~", 1, ""),
    ("NilClass", "^", 1, ""),
    ("NilClass", "inspect", 0, ""),
    ("NilClass", "nil?", 0, ""),
    ("NilClass", "rationalize", -1, "opt:eps"),
    ("NilClass", "to_a", 0, ""),
    ("NilClass", "to_c", 0, ""),
    ("NilClass", "to_f", 0, ""),
    ("NilClass", "to_h", 0, ""),
    ("NilClass", "to_i", 0, ""),
    ("NilClass", "to_r", 0, ""),
    ("NilClass", "to_s", 0, ""),
    ("NilClass", "|", 1, ""),
    ("NoMethodError", "args", 0, ""),
    ("NoMethodError", "initialize", -1, ""),
    ("NoMethodError", "private_call?", 0, ""),
    ("Numeric", "%", 1, ""),
    ("Numeric", "+@", 0, ""),
    ("Numeric", "-@", 0, ""),
    ("Numeric", "<=>", 1, ""),
    ("Numeric", "abs", 0, ""),
    ("Numeric", "abs2", 0, ""),
    ("Numeric", "angle", 0, ""),
    ("Numeric", "arg", 0, ""),
    ("Numeric", "ceil", -1, ""),
    ("Numeric", "clone", -1, ""),
    ("Numeric", "coerce", 1, ""),
    ("Numeric", "conj", 0, ""),
    ("Numeric", "conjugate", 0, ""),
    ("Numeric", "denominator", 0, ""),
    ("Numeric", "div", 1, ""),
    ("Numeric", "divmod", 1, ""),
    ("Numeric", "dup", 0, ""),
    ("Numeric", "eql?", 1, ""),
    ("Numeric", "fdiv", 1, ""),
    ("Numeric", "finite?", 0, ""),
    ("Numeric", "floor", -1, ""),
    ("Numeric", "i", 0, ""),
    ("Numeric", "imag", 0, ""),
    ("Numeric", "imaginary", 0, ""),
    ("Numeric", "infinite?", 0, ""),
    ("Numeric", "integer?", 0, ""),
    ("Numeric", "magnitude", 0, ""),
    ("Numeric", "modulo", 1, ""),
    ("Numeric", "negative?", 0, ""),
    ("Numeric", "nonzero?", 0, ""),
    ("Numeric", "numerator", 0, ""),
    ("Numeric", "phase", 0, ""),
    ("Numeric", "polar", 0, ""),
    ("Numeric", "positive?", 0, ""),
    ("Numeric", "quo", 1, ""),
    ("Numeric", "real", 0, ""),
    ("Numeric", "real?", 0, ""),
    ("Numeric", "rect", 0, ""),
    ("Numeric", "rectangular", 0, ""),
    ("Numeric", "remainder", 1, ""),
    ("Numeric", "round", -1, ""),
    ("Numeric", "singleton_method_added", 1, ""),
    ("Numeric", "step", -1, ""),
    ("Numeric", "to_c", 0, ""),
    ("Numeric", "to_int", 0, ""),
    ("Numeric", "truncate", -1, ""),
    ("Numeric", "zero?", 0, ""),
    ("Object", "derived_params", 1, "req:arity"),
    ("Object", "encode_params", 1, "req:ps"),
    ("Object", "esc", 1, "req:s"),
    ("ObjectSpace", "_id2ref", 1, ""),
    ("ObjectSpace", "count_objects", -1, ""),
    ("ObjectSpace", "define_finalizer", -1, ""),
    ("ObjectSpace", "each_object", -1, ""),
    (
        "ObjectSpace",
        "garbage_collect",
        -1,
        "key:full_mark,key:immediate_mark,key:immediate_sweep",
    ),
    ("ObjectSpace", "undefine_finalizer", 1, ""),
    ("Proc", "<<", 1, ""),
    ("Proc", "==", 1, ""),
    ("Proc", "===", -1, ""),
    ("Proc", ">>", 1, ""),
    ("Proc", "[]", -1, ""),
    ("Proc", "arity", 0, ""),
    ("Proc", "binding", 0, ""),
    ("Proc", "call", -1, ""),
    ("Proc", "clone", 0, ""),
    ("Proc", "curry", -1, ""),
    ("Proc", "dup", 0, ""),
    ("Proc", "eql?", 1, ""),
    ("Proc", "hash", 0, ""),
    ("Proc", "inspect", 0, ""),
    ("Proc", "lambda?", 0, ""),
    ("Proc", "parameters", -1, ""),
    ("Proc", "ruby2_keywords", 0, ""),
    ("Proc", "source_location", 0, ""),
    ("Proc", "to_proc", 0, ""),
    ("Proc", "to_s", 0, ""),
    ("Proc", "yield", -1, ""),
    ("Process", "argv0", 0, ""),
    ("Process", "clock_getres", -1, ""),
    ("Process", "clock_gettime", -1, ""),
    ("Process", "daemon", -1, ""),
    ("Process", "detach", 1, ""),
    ("Process", "egid", 0, ""),
    ("Process", "egid=", 1, ""),
    ("Process", "euid", 0, ""),
    ("Process", "euid=", 1, ""),
    ("Process", "getpgid", 1, ""),
    ("Process", "getpgrp", 0, ""),
    ("Process", "getpriority", 2, ""),
    ("Process", "getrlimit", 1, ""),
    ("Process", "getsid", -1, ""),
    ("Process", "gid", 0, ""),
    ("Process", "gid=", 1, ""),
    ("Process", "groups", 0, ""),
    ("Process", "groups=", 1, ""),
    ("Process", "initgroups", 2, ""),
    ("Process", "kill", -1, ""),
    ("Process", "maxgroups", 0, ""),
    ("Process", "maxgroups=", 1, ""),
    ("Process", "pid", 0, ""),
    ("Process", "ppid", 0, ""),
    ("Process", "setpgid", 2, ""),
    ("Process", "setpgrp", 0, ""),
    ("Process", "setpriority", 3, ""),
    ("Process", "setproctitle", 1, ""),
    ("Process", "setrlimit", -1, ""),
    ("Process", "setsid", 0, ""),
    ("Process", "times", 0, ""),
    ("Process", "uid", 0, ""),
    ("Process", "uid=", 1, ""),
    ("Process", "wait", -1, ""),
    ("Process", "wait2", -1, ""),
    ("Process", "waitall", 0, ""),
    ("Process", "waitpid", -1, ""),
    ("Process", "waitpid2", -1, ""),
    ("Process", "warmup", 0, ""),
    ("Random", "==", 1, ""),
    ("Random", "initialize_copy", 1, ""),
    ("Random", "left", 0, ""),
    ("Random", "marshal_dump", 0, ""),
    ("Random", "marshal_load", 1, ""),
    ("Random", "state", 0, ""),
    ("Random::Base", "bytes", 1, ""),
    ("Random::Base", "rand", -1, ""),
    ("Random::Base", "seed", 0, ""),
    ("Random::Formatter", "random_number", -1, ""),
    ("Range", "%", 1, ""),
    ("Range", "==", 1, ""),
    ("Range", "===", 1, ""),
    ("Range", "begin", 0, ""),
    ("Range", "bsearch", 0, ""),
    ("Range", "count", -1, ""),
    ("Range", "cover?", 1, ""),
    ("Range", "each", 0, ""),
    ("Range", "end", 0, ""),
    ("Range", "entries", 0, ""),
    ("Range", "eql?", 1, ""),
    ("Range", "exclude_end?", 0, ""),
    ("Range", "first", -1, ""),
    ("Range", "hash", 0, ""),
    ("Range", "include?", 1, ""),
    ("Range", "initialize", -1, ""),
    ("Range", "initialize_copy", 1, ""),
    ("Range", "inspect", 0, ""),
    ("Range", "last", -1, ""),
    ("Range", "max", -1, ""),
    ("Range", "member?", 1, ""),
    ("Range", "min", -1, ""),
    ("Range", "minmax", 0, ""),
    ("Range", "overlap?", 1, ""),
    ("Range", "reverse_each", 0, ""),
    ("Range", "size", 0, ""),
    ("Range", "step", -1, ""),
    ("Range", "to_a", 0, ""),
    ("Range", "to_s", 0, ""),
    ("Range", "to_set", -1, ""),
    ("Rational", "*", 1, ""),
    ("Rational", "**", 1, ""),
    ("Rational", "+", 1, ""),
    ("Rational", "-", 1, ""),
    ("Rational", "-@", 0, ""),
    ("Rational", "/", 1, ""),
    ("Rational", "<=>", 1, ""),
    ("Rational", "==", 1, ""),
    ("Rational", "abs", 0, ""),
    ("Rational", "ceil", -1, ""),
    ("Rational", "coerce", 1, ""),
    ("Rational", "denominator", 0, ""),
    ("Rational", "fdiv", 1, ""),
    ("Rational", "floor", -1, ""),
    ("Rational", "hash", 0, ""),
    ("Rational", "inspect", 0, ""),
    ("Rational", "magnitude", 0, ""),
    ("Rational", "marshal_dump", 0, ""),
    ("Rational", "negative?", 0, ""),
    ("Rational", "numerator", 0, ""),
    ("Rational", "positive?", 0, ""),
    ("Rational", "quo", 1, ""),
    ("Rational", "rationalize", -1, ""),
    ("Rational", "round", -1, ""),
    ("Rational", "to_f", 0, ""),
    ("Rational", "to_i", 0, ""),
    ("Rational", "to_r", 0, ""),
    ("Rational", "to_s", 0, ""),
    ("Rational", "truncate", -1, ""),
    ("Regexp", "==", 1, ""),
    ("Regexp", "===", 1, ""),
    ("Regexp", "=~", 1, ""),
    ("Regexp", "casefold?", 0, ""),
    ("Regexp", "encoding", 0, ""),
    ("Regexp", "eql?", 1, ""),
    ("Regexp", "fixed_encoding?", 0, ""),
    ("Regexp", "hash", 0, ""),
    ("Regexp", "initialize", -1, ""),
    ("Regexp", "initialize_copy", 1, ""),
    ("Regexp", "inspect", 0, ""),
    ("Regexp", "match", -1, ""),
    ("Regexp", "match?", -1, ""),
    ("Regexp", "named_captures", 0, ""),
    ("Regexp", "names", 0, ""),
    ("Regexp", "options", 0, ""),
    ("Regexp", "source", 0, ""),
    ("Regexp", "timeout", 0, ""),
    ("Regexp", "to_s", 0, ""),
    ("Regexp", "~", 0, ""),
    ("Set", "&", 1, ""),
    ("Set", "+", 1, ""),
    ("Set", "-", 1, ""),
    ("Set", "<", 1, ""),
    ("Set", "<<", 1, ""),
    ("Set", "<=", 1, ""),
    ("Set", "<=>", 1, ""),
    ("Set", "==", 1, ""),
    ("Set", "===", 1, ""),
    ("Set", ">", 1, ""),
    ("Set", ">=", 1, ""),
    ("Set", "^", 1, ""),
    ("Set", "add", 1, ""),
    ("Set", "add?", 1, ""),
    ("Set", "classify", 0, ""),
    ("Set", "clear", 0, ""),
    ("Set", "collect!", 0, ""),
    ("Set", "compare_by_identity", 0, ""),
    ("Set", "compare_by_identity?", 0, ""),
    ("Set", "delete", 1, ""),
    ("Set", "delete?", 1, ""),
    ("Set", "delete_if", 0, ""),
    ("Set", "difference", 1, ""),
    ("Set", "disjoint?", 1, ""),
    ("Set", "divide", 0, ""),
    ("Set", "each", 0, ""),
    ("Set", "empty?", 0, ""),
    ("Set", "eql?", 1, ""),
    ("Set", "filter!", 0, ""),
    ("Set", "flatten", 0, ""),
    ("Set", "flatten!", 0, ""),
    ("Set", "hash", 0, ""),
    ("Set", "include?", 1, ""),
    ("Set", "initialize", -1, ""),
    ("Set", "initialize_copy", 1, ""),
    ("Set", "inspect", 0, ""),
    ("Set", "intersect?", 1, ""),
    ("Set", "intersection", 1, ""),
    ("Set", "join", -1, ""),
    ("Set", "keep_if", 0, ""),
    ("Set", "length", 0, ""),
    ("Set", "map!", 0, ""),
    ("Set", "member?", 1, ""),
    ("Set", "merge", -1, ""),
    ("Set", "proper_subset?", 1, ""),
    ("Set", "proper_superset?", 1, ""),
    ("Set", "reject!", 0, ""),
    ("Set", "replace", 1, ""),
    ("Set", "reset", 0, ""),
    ("Set", "select!", 0, ""),
    ("Set", "size", 0, ""),
    ("Set", "subset?", 1, ""),
    ("Set", "subtract", 1, ""),
    ("Set", "superset?", 1, ""),
    ("Set", "to_a", 0, ""),
    ("Set", "to_s", 0, ""),
    ("Set", "to_set", -1, ""),
    ("Set", "union", 1, ""),
    ("Set", "|", 1, ""),
    ("Signal", "list", 0, ""),
    ("Signal", "signame", 1, ""),
    ("Signal", "trap", -1, ""),
    ("StopIteration", "result", 0, ""),
    ("String", "%", 1, ""),
    ("String", "*", 1, ""),
    ("String", "+", 1, ""),
    ("String", "+@", 0, ""),
    ("String", "-@", 0, ""),
    ("String", "<<", 1, ""),
    ("String", "<=>", 1, ""),
    ("String", "==", 1, ""),
    ("String", "===", 1, ""),
    ("String", "=~", 1, ""),
    ("String", "[]", -1, ""),
    ("String", "[]=", -1, ""),
    ("String", "append_as_bytes", -1, ""),
    ("String", "ascii_only?", 0, ""),
    ("String", "b", 0, ""),
    ("String", "byteindex", -1, ""),
    ("String", "byterindex", -1, ""),
    ("String", "bytes", 0, ""),
    ("String", "bytesize", 0, ""),
    ("String", "byteslice", -1, ""),
    ("String", "bytesplice", -1, ""),
    ("String", "capitalize", -1, ""),
    ("String", "capitalize!", -1, ""),
    ("String", "casecmp", 1, ""),
    ("String", "casecmp?", 1, ""),
    ("String", "center", -1, ""),
    ("String", "chars", 0, ""),
    ("String", "chomp", -1, ""),
    ("String", "chomp!", -1, ""),
    ("String", "chop", 0, ""),
    ("String", "chop!", 0, ""),
    ("String", "chr", 0, ""),
    ("String", "clear", 0, ""),
    ("String", "codepoints", 0, ""),
    ("String", "concat", -1, ""),
    ("String", "count", -1, ""),
    ("String", "crypt", 1, ""),
    ("String", "dedup", 0, ""),
    ("String", "delete", -1, ""),
    ("String", "delete!", -1, ""),
    ("String", "delete_prefix", 1, ""),
    ("String", "delete_prefix!", 1, ""),
    ("String", "delete_suffix", 1, ""),
    ("String", "delete_suffix!", 1, ""),
    ("String", "downcase", -1, ""),
    ("String", "downcase!", -1, ""),
    ("String", "dump", 0, ""),
    ("String", "dup", 0, ""),
    ("String", "each_byte", 0, ""),
    ("String", "each_char", 0, ""),
    ("String", "each_codepoint", 0, ""),
    ("String", "each_grapheme_cluster", 0, ""),
    ("String", "each_line", -1, ""),
    ("String", "empty?", 0, ""),
    ("String", "encode", -1, ""),
    ("String", "encode!", -1, ""),
    ("String", "encoding", 0, ""),
    ("String", "end_with?", -1, ""),
    ("String", "eql?", 1, ""),
    ("String", "force_encoding", 1, ""),
    ("String", "freeze", 0, ""),
    ("String", "getbyte", 1, ""),
    ("String", "grapheme_clusters", 0, ""),
    ("String", "gsub", -1, ""),
    ("String", "gsub!", -1, ""),
    ("String", "hash", 0, ""),
    ("String", "hex", 0, ""),
    ("String", "include?", 1, ""),
    ("String", "index", -1, ""),
    ("String", "initialize", -1, ""),
    ("String", "initialize_copy", 1, ""),
    ("String", "insert", 2, ""),
    ("String", "inspect", 0, ""),
    ("String", "intern", 0, ""),
    ("String", "length", 0, ""),
    ("String", "lines", -1, ""),
    ("String", "ljust", -1, ""),
    ("String", "lstrip", -1, ""),
    ("String", "lstrip!", -1, ""),
    ("String", "match", -1, ""),
    ("String", "match?", -1, ""),
    ("String", "next", 0, ""),
    ("String", "next!", 0, ""),
    ("String", "oct", 0, ""),
    ("String", "ord", 0, ""),
    ("String", "partition", 1, ""),
    ("String", "prepend", -1, ""),
    ("String", "replace", 1, ""),
    ("String", "reverse", 0, ""),
    ("String", "reverse!", 0, ""),
    ("String", "rindex", -1, ""),
    ("String", "rjust", -1, ""),
    ("String", "rpartition", 1, ""),
    ("String", "rstrip", -1, ""),
    ("String", "rstrip!", -1, ""),
    ("String", "scan", 1, ""),
    ("String", "scrub", -1, ""),
    ("String", "scrub!", -1, ""),
    ("String", "setbyte", 2, ""),
    ("String", "size", 0, ""),
    ("String", "slice", -1, ""),
    ("String", "slice!", -1, ""),
    ("String", "split", -1, ""),
    ("String", "squeeze", -1, ""),
    ("String", "squeeze!", -1, ""),
    ("String", "start_with?", -1, ""),
    ("String", "strip", -1, ""),
    ("String", "strip!", -1, ""),
    ("String", "sub", -1, ""),
    ("String", "sub!", -1, ""),
    ("String", "succ", 0, ""),
    ("String", "succ!", 0, ""),
    ("String", "sum", -1, ""),
    ("String", "swapcase", -1, ""),
    ("String", "swapcase!", -1, ""),
    ("String", "to_c", 0, ""),
    ("String", "to_f", 0, ""),
    ("String", "to_i", -1, ""),
    ("String", "to_r", 0, ""),
    ("String", "to_s", 0, ""),
    ("String", "to_str", 0, ""),
    ("String", "to_sym", 0, ""),
    ("String", "tr", 2, ""),
    ("String", "tr!", 2, ""),
    ("String", "tr_s", 2, ""),
    ("String", "tr_s!", 2, ""),
    ("String", "undump", 0, ""),
    ("String", "unicode_normalize", -1, ""),
    ("String", "unicode_normalize!", -1, ""),
    ("String", "unicode_normalized?", -1, ""),
    ("String", "unpack", -2, "req:fmt,key:offset"),
    ("String", "unpack1", -2, "req:fmt,key:offset"),
    ("String", "upcase", -1, ""),
    ("String", "upcase!", -1, ""),
    ("String", "upto", -1, ""),
    ("String", "valid_encoding?", 0, ""),
    ("Struct", "==", 1, ""),
    ("Struct", "[]", 1, ""),
    ("Struct", "[]=", 2, ""),
    ("Struct", "deconstruct", 0, ""),
    ("Struct", "deconstruct_keys", 1, ""),
    ("Struct", "dig", -1, ""),
    ("Struct", "each", 0, ""),
    ("Struct", "each_pair", 0, ""),
    ("Struct", "eql?", 1, ""),
    ("Struct", "filter", -1, ""),
    ("Struct", "hash", 0, ""),
    ("Struct", "initialize", -1, ""),
    ("Struct", "initialize_copy", 1, ""),
    ("Struct", "inspect", 0, ""),
    ("Struct", "length", 0, ""),
    ("Struct", "members", 0, ""),
    ("Struct", "select", -1, ""),
    ("Struct", "size", 0, ""),
    ("Struct", "to_a", 0, ""),
    ("Struct", "to_h", 0, ""),
    ("Struct", "to_s", 0, ""),
    ("Struct", "values", 0, ""),
    ("Struct", "values_at", -1, ""),
    ("Symbol", "<=>", 1, ""),
    ("Symbol", "==", 1, ""),
    ("Symbol", "===", 1, ""),
    ("Symbol", "=~", 1, ""),
    ("Symbol", "[]", -1, ""),
    ("Symbol", "capitalize", -1, ""),
    ("Symbol", "casecmp", 1, ""),
    ("Symbol", "casecmp?", 1, ""),
    ("Symbol", "downcase", -1, ""),
    ("Symbol", "empty?", 0, ""),
    ("Symbol", "encoding", 0, ""),
    ("Symbol", "end_with?", -1, ""),
    ("Symbol", "id2name", 0, ""),
    ("Symbol", "inspect", 0, ""),
    ("Symbol", "intern", 0, ""),
    ("Symbol", "length", 0, ""),
    ("Symbol", "match", -1, ""),
    ("Symbol", "match?", -1, ""),
    ("Symbol", "name", 0, ""),
    ("Symbol", "next", 0, ""),
    ("Symbol", "size", 0, ""),
    ("Symbol", "slice", -1, ""),
    ("Symbol", "start_with?", -1, ""),
    ("Symbol", "succ", 0, ""),
    ("Symbol", "swapcase", -1, ""),
    ("Symbol", "to_proc", 0, ""),
    ("Symbol", "to_s", 0, ""),
    ("Symbol", "to_sym", 0, ""),
    ("Symbol", "upcase", -1, ""),
    ("SystemExit", "initialize", -1, ""),
    ("SystemExit", "status", 0, ""),
    ("SystemExit", "success?", 0, ""),
    ("Thread", "[]", 1, ""),
    ("Thread", "[]=", 2, ""),
    ("Thread", "abort_on_exception", 0, ""),
    ("Thread", "abort_on_exception=", 1, ""),
    ("Thread", "add_trace_func", 1, ""),
    ("Thread", "alive?", 0, ""),
    ("Thread", "backtrace", -1, ""),
    ("Thread", "backtrace_locations", -1, ""),
    ("Thread", "exit", 0, ""),
    ("Thread", "fetch", -1, ""),
    ("Thread", "group", 0, ""),
    ("Thread", "initialize", -1, ""),
    ("Thread", "inspect", 0, ""),
    ("Thread", "join", -1, ""),
    ("Thread", "key?", 1, ""),
    ("Thread", "keys", 0, ""),
    ("Thread", "kill", 0, ""),
    ("Thread", "name", 0, ""),
    ("Thread", "name=", 1, ""),
    ("Thread", "native_thread_id", 0, ""),
    ("Thread", "pending_interrupt?", -1, ""),
    ("Thread", "priority", 0, ""),
    ("Thread", "priority=", 1, ""),
    ("Thread", "raise", -1, ""),
    ("Thread", "report_on_exception", 0, ""),
    ("Thread", "report_on_exception=", 1, ""),
    ("Thread", "run", 0, ""),
    ("Thread", "set_trace_func", 1, ""),
    ("Thread", "status", 0, ""),
    ("Thread", "stop?", 0, ""),
    ("Thread", "terminate", 0, ""),
    ("Thread", "thread_variable?", 1, ""),
    ("Thread", "thread_variable_get", 1, ""),
    ("Thread", "thread_variable_set", 2, ""),
    ("Thread", "thread_variables", 0, ""),
    ("Thread", "to_s", 0, ""),
    ("Thread", "value", 0, ""),
    ("Thread", "wakeup", 0, ""),
    ("Thread::ConditionVariable", "broadcast", 0, ""),
    ("Thread::ConditionVariable", "initialize", 0, ""),
    ("Thread::ConditionVariable", "marshal_dump", 0, ""),
    ("Thread::ConditionVariable", "signal", 0, ""),
    (
        "Thread::ConditionVariable",
        "wait",
        -2,
        "req:mutex,opt:timeout",
    ),
    ("Thread::Mutex", "initialize", 0, ""),
    ("Thread::Mutex", "lock", 0, ""),
    ("Thread::Mutex", "locked?", 0, ""),
    ("Thread::Mutex", "owned?", 0, ""),
    ("Thread::Mutex", "sleep", -1, "opt:timeout"),
    ("Thread::Mutex", "synchronize", 0, ""),
    ("Thread::Mutex", "try_lock", 0, ""),
    ("Thread::Mutex", "unlock", 0, ""),
    ("Thread::Queue", "<<", 1, ""),
    ("Thread::Queue", "clear", 0, ""),
    ("Thread::Queue", "close", 0, ""),
    ("Thread::Queue", "closed?", 0, ""),
    ("Thread::Queue", "deq", -1, "opt:non_block,key:timeout"),
    ("Thread::Queue", "empty?", 0, ""),
    ("Thread::Queue", "enq", 1, ""),
    ("Thread::Queue", "freeze", 0, ""),
    ("Thread::Queue", "initialize", -1, ""),
    ("Thread::Queue", "length", 0, ""),
    ("Thread::Queue", "marshal_dump", 0, ""),
    ("Thread::Queue", "num_waiting", 0, ""),
    ("Thread::Queue", "pop", -1, "opt:non_block,key:timeout"),
    ("Thread::Queue", "push", 1, ""),
    ("Thread::Queue", "shift", -1, "opt:non_block,key:timeout"),
    ("Thread::Queue", "size", 0, ""),
    (
        "Thread::SizedQueue",
        "<<",
        -2,
        "req:object,opt:non_block,key:timeout",
    ),
    ("Thread::SizedQueue", "clear", 0, ""),
    ("Thread::SizedQueue", "close", 0, ""),
    ("Thread::SizedQueue", "deq", -1, "opt:non_block,key:timeout"),
    (
        "Thread::SizedQueue",
        "enq",
        -2,
        "req:object,opt:non_block,key:timeout",
    ),
    ("Thread::SizedQueue", "initialize", 1, ""),
    ("Thread::SizedQueue", "max", 0, ""),
    ("Thread::SizedQueue", "max=", 1, ""),
    ("Thread::SizedQueue", "num_waiting", 0, ""),
    ("Thread::SizedQueue", "pop", -1, "opt:non_block,key:timeout"),
    (
        "Thread::SizedQueue",
        "push",
        -2,
        "req:object,opt:non_block,key:timeout",
    ),
    (
        "Thread::SizedQueue",
        "shift",
        -1,
        "opt:non_block,key:timeout",
    ),
    ("Time", "+", 1, ""),
    ("Time", "-", 1, ""),
    ("Time", "<=>", 1, ""),
    ("Time", "_dump", -1, ""),
    ("Time", "asctime", 0, ""),
    ("Time", "ceil", -1, ""),
    ("Time", "ctime", 0, ""),
    ("Time", "day", 0, ""),
    ("Time", "deconstruct_keys", 1, ""),
    ("Time", "dst?", 0, ""),
    ("Time", "eql?", 1, ""),
    ("Time", "floor", -1, ""),
    ("Time", "friday?", 0, ""),
    ("Time", "getgm", 0, ""),
    ("Time", "getlocal", -1, ""),
    ("Time", "getutc", 0, ""),
    ("Time", "gmt?", 0, ""),
    ("Time", "gmt_offset", 0, ""),
    ("Time", "gmtime", 0, ""),
    ("Time", "gmtoff", 0, ""),
    ("Time", "hash", 0, ""),
    ("Time", "hour", 0, ""),
    (
        "Time",
        "initialize",
        -1,
        "opt:year,opt:mon,opt:mday,opt:hour,opt:min,opt:sec,opt:zone,key:in,key:precision",
    ),
    ("Time", "initialize_copy", 1, ""),
    ("Time", "inspect", 0, ""),
    ("Time", "isdst", 0, ""),
    ("Time", "iso8601", -1, ""),
    ("Time", "localtime", -1, ""),
    ("Time", "mday", 0, ""),
    ("Time", "min", 0, ""),
    ("Time", "mon", 0, ""),
    ("Time", "monday?", 0, ""),
    ("Time", "month", 0, ""),
    ("Time", "nsec", 0, ""),
    ("Time", "round", -1, ""),
    ("Time", "saturday?", 0, ""),
    ("Time", "sec", 0, ""),
    ("Time", "strftime", 1, ""),
    ("Time", "subsec", 0, ""),
    ("Time", "sunday?", 0, ""),
    ("Time", "thursday?", 0, ""),
    ("Time", "to_a", 0, ""),
    ("Time", "to_f", 0, ""),
    ("Time", "to_i", 0, ""),
    ("Time", "to_r", 0, ""),
    ("Time", "to_s", 0, ""),
    ("Time", "tuesday?", 0, ""),
    ("Time", "tv_nsec", 0, ""),
    ("Time", "tv_sec", 0, ""),
    ("Time", "tv_usec", 0, ""),
    ("Time", "usec", 0, ""),
    ("Time", "utc", 0, ""),
    ("Time", "utc?", 0, ""),
    ("Time", "utc_offset", 0, ""),
    ("Time", "wday", 0, ""),
    ("Time", "wednesday?", 0, ""),
    ("Time", "xmlschema", -1, ""),
    ("Time", "yday", 0, ""),
    ("Time", "year", 0, ""),
    ("Time", "zone", 0, ""),
    ("TrueClass", "&", 1, ""),
    ("TrueClass", "===", 1, ""),
    ("TrueClass", "^", 1, ""),
    ("TrueClass", "inspect", 0, ""),
    ("TrueClass", "to_s", 0, ""),
    ("TrueClass", "|", 1, ""),
    ("UnboundMethod", "==", 1, ""),
    ("UnboundMethod", "arity", 0, ""),
    ("UnboundMethod", "bind", 1, ""),
    ("UnboundMethod", "bind_call", -1, ""),
    ("UnboundMethod", "clone", 0, ""),
    ("UnboundMethod", "dup", 0, ""),
    ("UnboundMethod", "eql?", 1, ""),
    ("UnboundMethod", "hash", 0, ""),
    ("UnboundMethod", "inspect", 0, ""),
    ("UnboundMethod", "name", 0, ""),
    ("UnboundMethod", "original_name", 0, ""),
    ("UnboundMethod", "owner", 0, ""),
    ("UnboundMethod", "parameters", 0, ""),
    ("UnboundMethod", "source_location", 0, ""),
    ("UnboundMethod", "super_method", 0, ""),
    ("UnboundMethod", "to_s", 0, ""),
    ("Warning", "warn", -1, ""),
];

/// The ancestor chain the reference interpreter reports for each built-in
/// class — the order `#owner` resolution walks. Sorted by class name.
pub static BUILTIN_ANCESTRY: &[(&str, &[&str])] = &[
    (
        "ArgumentError",
        &[
            "ArgumentError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Array",
        &["Array", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    ("BasicObject", &["BasicObject"]),
    ("Binding", &["Binding", "Object", "Kernel", "BasicObject"]),
    (
        "Class",
        &["Class", "Module", "Object", "Kernel", "BasicObject"],
    ),
    ("Comparable", &["Comparable"]),
    (
        "Complex",
        &[
            "Complex",
            "Numeric",
            "Comparable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("Data", &["Data", "Object", "Kernel", "BasicObject"]),
    (
        "Dir",
        &["Dir", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    ("Encoding", &["Encoding", "Object", "Kernel", "BasicObject"]),
    ("Enumerable", &["Enumerable"]),
    (
        "Enumerator",
        &[
            "Enumerator",
            "Enumerable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Enumerator::Lazy",
        &[
            "Enumerator::Lazy",
            "Enumerator",
            "Enumerable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Enumerator::Yielder",
        &["Enumerator::Yielder", "Object", "Kernel", "BasicObject"],
    ),
    (
        "Exception",
        &["Exception", "Object", "Kernel", "BasicObject"],
    ),
    (
        "FalseClass",
        &["FalseClass", "Object", "Kernel", "BasicObject"],
    ),
    ("Fiber", &["Fiber", "Object", "Kernel", "BasicObject"]),
    (
        "File",
        &[
            "File",
            "IO",
            "File::Constants",
            "Enumerable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("FileTest", &["FileTest"]),
    (
        "Float",
        &[
            "Float",
            "Numeric",
            "Comparable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "FrozenError",
        &[
            "FrozenError",
            "RuntimeError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("GC", &["GC"]),
    (
        "Hash",
        &["Hash", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "IO",
        &[
            "IO",
            "File::Constants",
            "Enumerable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "IOError",
        &[
            "IOError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "IndexError",
        &[
            "IndexError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Integer",
        &[
            "Integer",
            "Numeric",
            "Comparable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("Kernel", &["Kernel"]),
    (
        "KeyError",
        &[
            "KeyError",
            "IndexError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "LocalJumpError",
        &[
            "LocalJumpError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("Marshal", &["Marshal"]),
    (
        "MatchData",
        &["MatchData", "Object", "Kernel", "BasicObject"],
    ),
    ("Math", &["Math"]),
    ("Method", &["Method", "Object", "Kernel", "BasicObject"]),
    ("Module", &["Module", "Object", "Kernel", "BasicObject"]),
    (
        "NameError",
        &[
            "NameError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("NilClass", &["NilClass", "Object", "Kernel", "BasicObject"]),
    (
        "NoMethodError",
        &[
            "NoMethodError",
            "NameError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "NotImplementedError",
        &[
            "NotImplementedError",
            "ScriptError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Numeric",
        &["Numeric", "Comparable", "Object", "Kernel", "BasicObject"],
    ),
    ("Object", &["Object", "Kernel", "BasicObject"]),
    ("ObjectSpace", &["ObjectSpace"]),
    ("Proc", &["Proc", "Object", "Kernel", "BasicObject"]),
    ("Process", &["Process"]),
    (
        "Random",
        &[
            "Random",
            "Random::Base",
            "Random::Formatter",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Range",
        &["Range", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "RangeError",
        &[
            "RangeError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Rational",
        &[
            "Rational",
            "Numeric",
            "Comparable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    ("Regexp", &["Regexp", "Object", "Kernel", "BasicObject"]),
    (
        "RuntimeError",
        &[
            "RuntimeError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Set",
        &["Set", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    ("Signal", &["Signal"]),
    (
        "StandardError",
        &[
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "StopIteration",
        &[
            "StopIteration",
            "IndexError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "String",
        &["String", "Comparable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "Struct",
        &["Struct", "Enumerable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "Symbol",
        &["Symbol", "Comparable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "SystemExit",
        &["SystemExit", "Exception", "Object", "Kernel", "BasicObject"],
    ),
    ("Thread", &["Thread", "Object", "Kernel", "BasicObject"]),
    (
        "Thread::ConditionVariable",
        &[
            "Thread::ConditionVariable",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Thread::Mutex",
        &["Thread::Mutex", "Object", "Kernel", "BasicObject"],
    ),
    (
        "Thread::Queue",
        &["Thread::Queue", "Object", "Kernel", "BasicObject"],
    ),
    (
        "Thread::SizedQueue",
        &[
            "Thread::SizedQueue",
            "Thread::Queue",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "Time",
        &["Time", "Comparable", "Object", "Kernel", "BasicObject"],
    ),
    (
        "TrueClass",
        &["TrueClass", "Object", "Kernel", "BasicObject"],
    ),
    (
        "TypeError",
        &[
            "TypeError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
    (
        "UnboundMethod",
        &["UnboundMethod", "Object", "Kernel", "BasicObject"],
    ),
    ("Warning", &["Warning"]),
    (
        "ZeroDivisionError",
        &[
            "ZeroDivisionError",
            "StandardError",
            "Exception",
            "Object",
            "Kernel",
            "BasicObject",
        ],
    ),
];

/// The built-in names that are modules, not classes — they have no `new`, and
/// their singleton chain skips `Class`. Sorted.
pub static BUILTIN_MODULES: &[&str] = &[
    "Comparable",
    "Enumerable",
    "File::Constants",
    "FileTest",
    "GC",
    "Kernel",
    "Marshal",
    "Math",
    "ObjectSpace",
    "Process",
    "Random::Formatter",
    "Signal",
    "Warning",
];

/// The row `(owner, arity, params)` the reference interpreter declares for
/// `method` on `owner`, or `None` when `owner` does not define it. The owner is
/// returned as the table's own `'static` string so callers can keep it.
pub fn lookup(owner: &str, method: &str) -> Option<(&'static str, i16, &'static str)> {
    BUILTIN_METHODS
        .binary_search_by(|(o, m, _, _)| (*o, *m).cmp(&(owner, method)))
        .ok()
        .map(|i| {
            (
                BUILTIN_METHODS[i].0,
                BUILTIN_METHODS[i].2,
                BUILTIN_METHODS[i].3,
            )
        })
}

/// The reference ancestor chain of built-in class `name`, or `None` when it is
/// not a built-in.
pub fn ancestry(name: &str) -> Option<&'static [&'static str]> {
    BUILTIN_ANCESTRY
        .binary_search_by(|(c, _)| c.cmp(&name))
        .ok()
        .map(|i| BUILTIN_ANCESTRY[i].1)
}

/// Whether `name` is a built-in module (as opposed to a class).
pub fn is_module(name: &str) -> bool {
    BUILTIN_MODULES.binary_search(&name).is_ok()
}

/// `Method#parameters` for a table row: the explicit list when the row carries
/// one, otherwise the list MRI reports for a C function of that arity — `n`
/// unnamed required parameters, and for a negative arity `-(n+1)` those `n`
/// followed by an unnamed rest.
pub fn params_for(arity: i16, params: &'static str) -> Vec<(&'static str, Option<String>)> {
    if !params.is_empty() {
        return params
            .split(',')
            .map(|tok| match tok.split_once(':') {
                Some((kind, name)) => (param_kind(kind), Some(name.to_string())),
                None => (param_kind(tok), None),
            })
            .collect();
    }
    let req = if arity >= 0 { arity } else { -arity - 1 };
    let mut out: Vec<(&'static str, Option<String>)> = (0..req).map(|_| ("req", None)).collect();
    if arity < 0 {
        out.push(("rest", None));
    }
    out
}

/// Intern a parameter-kind token from the table back to a `'static` name.
fn param_kind(k: &str) -> &'static str {
    match k {
        "req" => "req",
        "opt" => "opt",
        "rest" => "rest",
        "keyreq" => "keyreq",
        "key" => "key",
        "keyrest" => "keyrest",
        "block" => "block",
        "nokey" => "nokey",
        other => Box::leak(other.to_string().into_boxed_str()),
    }
}
