//! Which of MRI's built-in methods are PRIVATE.
//!
//! [`crate::arity_table`] lists every built-in by defining module but does not
//! record visibility, and `respond_to?` must: `3.respond_to?(:puts)` is false
//! while `3.respond_to?(:puts, true)` is true, and `Object.new.respond_to?(:to_s)`
//! is true. Each row here is a `(owner, method)` row of that table which the
//! reference interpreter reports in `owner.private_instance_methods(false)`.
//!
//! Derived from the reference interpreter, named by ABSOLUTE PATH (bare `ruby`
//! is rubylang itself wherever it is installed):
//!
//! ```text
//! /opt/homebrew/opt/ruby/bin/ruby -e '
//!   src = File.read("src/arity_table.rs")[/BUILTIN_METHODS: .*?\n\];/m]
//!   src.scan(/\(\s*"([^"]+)",\s*"([^"]+)",\s*-?\d+,/m).select { |o, m|
//!     k = (Object.const_get(o) rescue nil)
//!     k && !o.start_with?("#<") && k.private_instance_methods(false).include?(m.to_sym)
//!   }.sort.each { |o, m| puts "    (#{o.inspect}, #{m.inspect})," }'
//! ```

/// `(owner, method)`, sorted for binary search.
static PRIVATE_BUILTIN_METHODS: &[(&str, &str)] = &[
    ("Array", "initialize"),
    ("Array", "initialize_copy"),
    ("BasicObject", "initialize"),
    ("BasicObject", "method_missing"),
    ("BasicObject", "singleton_method_added"),
    ("BasicObject", "singleton_method_removed"),
    ("BasicObject", "singleton_method_undefined"),
    ("Class", "inherited"),
    ("Class", "initialize"),
    ("Complex", "marshal_dump"),
    ("Data", "initialize"),
    ("Data", "initialize_copy"),
    ("Dir", "initialize"),
    ("Enumerator", "initialize"),
    ("Enumerator", "initialize_copy"),
    ("Enumerator::Lazy", "_enumerable_collect"),
    ("Enumerator::Lazy", "_enumerable_collect_concat"),
    ("Enumerator::Lazy", "_enumerable_drop"),
    ("Enumerator::Lazy", "_enumerable_drop_while"),
    ("Enumerator::Lazy", "_enumerable_filter"),
    ("Enumerator::Lazy", "_enumerable_filter_map"),
    ("Enumerator::Lazy", "_enumerable_find_all"),
    ("Enumerator::Lazy", "_enumerable_flat_map"),
    ("Enumerator::Lazy", "_enumerable_grep"),
    ("Enumerator::Lazy", "_enumerable_grep_v"),
    ("Enumerator::Lazy", "_enumerable_map"),
    ("Enumerator::Lazy", "_enumerable_reject"),
    ("Enumerator::Lazy", "_enumerable_select"),
    ("Enumerator::Lazy", "_enumerable_take"),
    ("Enumerator::Lazy", "_enumerable_take_while"),
    ("Enumerator::Lazy", "_enumerable_uniq"),
    ("Enumerator::Lazy", "_enumerable_with_index"),
    ("Enumerator::Lazy", "_enumerable_zip"),
    ("Enumerator::Lazy", "initialize"),
    ("Enumerator::Yielder", "initialize"),
    ("Exception", "initialize"),
    ("Exception", "method_missing"),
    ("Exception", "respond_to_missing?"),
    ("Fiber", "initialize"),
    ("File", "initialize"),
    ("FileTest", "blockdev?"),
    ("FileTest", "chardev?"),
    ("FileTest", "directory?"),
    ("FileTest", "empty?"),
    ("FileTest", "executable?"),
    ("FileTest", "executable_real?"),
    ("FileTest", "exist?"),
    ("FileTest", "file?"),
    ("FileTest", "grpowned?"),
    ("FileTest", "identical?"),
    ("FileTest", "owned?"),
    ("FileTest", "pipe?"),
    ("FileTest", "readable?"),
    ("FileTest", "readable_real?"),
    ("FileTest", "setgid?"),
    ("FileTest", "setuid?"),
    ("FileTest", "size"),
    ("FileTest", "size?"),
    ("FileTest", "socket?"),
    ("FileTest", "sticky?"),
    ("FileTest", "symlink?"),
    ("FileTest", "world_readable?"),
    ("FileTest", "world_writable?"),
    ("FileTest", "writable?"),
    ("FileTest", "writable_real?"),
    ("FileTest", "zero?"),
    ("FrozenError", "initialize"),
    ("Hash", "initialize"),
    ("Hash", "initialize_copy"),
    ("IO", "initialize"),
    ("IO", "initialize_copy"),
    ("Kernel", "Array"),
    ("Kernel", "Complex"),
    ("Kernel", "Float"),
    ("Kernel", "Hash"),
    ("Kernel", "Integer"),
    ("Kernel", "Pathname"),
    ("Kernel", "Rational"),
    ("Kernel", "String"),
    ("Kernel", "__callee__"),
    ("Kernel", "__dir__"),
    ("Kernel", "__method__"),
    ("Kernel", "`"),
    ("Kernel", "abort"),
    ("Kernel", "at_exit"),
    ("Kernel", "autoload"),
    ("Kernel", "autoload?"),
    ("Kernel", "binding"),
    ("Kernel", "block_given?"),
    ("Kernel", "caller"),
    ("Kernel", "caller_locations"),
    ("Kernel", "catch"),
    ("Kernel", "eval"),
    ("Kernel", "exec"),
    ("Kernel", "exit"),
    ("Kernel", "exit!"),
    ("Kernel", "fail"),
    ("Kernel", "fork"),
    ("Kernel", "format"),
    ("Kernel", "gem"),
    ("Kernel", "gem_original_require"),
    ("Kernel", "gets"),
    ("Kernel", "global_variables"),
    ("Kernel", "initialize_clone"),
    ("Kernel", "initialize_copy"),
    ("Kernel", "initialize_dup"),
    ("Kernel", "instance_variables_to_inspect"),
    ("Kernel", "iterator?"),
    ("Kernel", "lambda"),
    ("Kernel", "load"),
    ("Kernel", "local_variables"),
    ("Kernel", "loop"),
    ("Kernel", "open"),
    ("Kernel", "p"),
    ("Kernel", "pp"),
    ("Kernel", "print"),
    ("Kernel", "printf"),
    ("Kernel", "proc"),
    ("Kernel", "putc"),
    ("Kernel", "puts"),
    ("Kernel", "raise"),
    ("Kernel", "rand"),
    ("Kernel", "readline"),
    ("Kernel", "readlines"),
    ("Kernel", "require"),
    ("Kernel", "require_relative"),
    ("Kernel", "respond_to_missing?"),
    ("Kernel", "select"),
    ("Kernel", "set_trace_func"),
    ("Kernel", "sleep"),
    ("Kernel", "spawn"),
    ("Kernel", "sprintf"),
    ("Kernel", "srand"),
    ("Kernel", "syscall"),
    ("Kernel", "system"),
    ("Kernel", "test"),
    ("Kernel", "throw"),
    ("Kernel", "trace_var"),
    ("Kernel", "trap"),
    ("Kernel", "untrace_var"),
    ("Kernel", "warn"),
    ("KeyError", "initialize"),
    ("Marshal", "dump"),
    ("MatchData", "initialize_copy"),
    ("Math", "acos"),
    ("Math", "acosh"),
    ("Math", "asin"),
    ("Math", "asinh"),
    ("Math", "atan"),
    ("Math", "atan2"),
    ("Math", "atanh"),
    ("Math", "cbrt"),
    ("Math", "cos"),
    ("Math", "cosh"),
    ("Math", "erf"),
    ("Math", "erfc"),
    ("Math", "exp"),
    ("Math", "expm1"),
    ("Math", "frexp"),
    ("Math", "gamma"),
    ("Math", "hypot"),
    ("Math", "ldexp"),
    ("Math", "lgamma"),
    ("Math", "log"),
    ("Math", "log10"),
    ("Math", "log1p"),
    ("Math", "log2"),
    ("Math", "sin"),
    ("Math", "sinh"),
    ("Math", "sqrt"),
    ("Math", "tan"),
    ("Math", "tanh"),
    ("Module", "append_features"),
    ("Module", "const_added"),
    ("Module", "extend_object"),
    ("Module", "extended"),
    ("Module", "included"),
    ("Module", "initialize"),
    ("Module", "initialize_clone"),
    ("Module", "method_added"),
    ("Module", "method_removed"),
    ("Module", "method_undefined"),
    ("Module", "module_function"),
    ("Module", "prepend_features"),
    ("Module", "prepended"),
    ("Module", "private"),
    ("Module", "protected"),
    ("Module", "public"),
    ("Module", "refine"),
    ("Module", "remove_const"),
    ("Module", "ruby2_keywords"),
    ("Module", "using"),
    ("NameError", "initialize"),
    ("NoMethodError", "initialize"),
    ("ObjectSpace", "_id2ref"),
    ("ObjectSpace", "count_objects"),
    ("ObjectSpace", "define_finalizer"),
    ("ObjectSpace", "each_object"),
    ("ObjectSpace", "garbage_collect"),
    ("ObjectSpace", "undefine_finalizer"),
    ("Process", "argv0"),
    ("Process", "clock_getres"),
    ("Process", "clock_gettime"),
    ("Process", "daemon"),
    ("Process", "detach"),
    ("Process", "egid"),
    ("Process", "egid="),
    ("Process", "euid"),
    ("Process", "euid="),
    ("Process", "getpgid"),
    ("Process", "getpgrp"),
    ("Process", "getpriority"),
    ("Process", "getrlimit"),
    ("Process", "getsid"),
    ("Process", "gid"),
    ("Process", "gid="),
    ("Process", "groups"),
    ("Process", "groups="),
    ("Process", "initgroups"),
    ("Process", "kill"),
    ("Process", "maxgroups"),
    ("Process", "maxgroups="),
    ("Process", "pid"),
    ("Process", "ppid"),
    ("Process", "setpgid"),
    ("Process", "setpgrp"),
    ("Process", "setpriority"),
    ("Process", "setproctitle"),
    ("Process", "setrlimit"),
    ("Process", "setsid"),
    ("Process", "times"),
    ("Process", "uid"),
    ("Process", "uid="),
    ("Process", "wait"),
    ("Process", "wait2"),
    ("Process", "waitall"),
    ("Process", "waitpid"),
    ("Process", "waitpid2"),
    ("Process", "warmup"),
    ("Random", "initialize_copy"),
    ("Random", "left"),
    ("Random", "marshal_dump"),
    ("Random", "marshal_load"),
    ("Random", "state"),
    ("Range", "initialize"),
    ("Range", "initialize_copy"),
    ("Rational", "marshal_dump"),
    ("Regexp", "initialize"),
    ("Regexp", "initialize_copy"),
    ("Set", "initialize"),
    ("Set", "initialize_copy"),
    ("Signal", "list"),
    ("Signal", "signame"),
    ("Signal", "trap"),
    ("String", "initialize"),
    ("String", "initialize_copy"),
    ("Struct", "initialize"),
    ("Struct", "initialize_copy"),
    ("SystemExit", "initialize"),
    ("Thread", "initialize"),
    ("Thread::ConditionVariable", "initialize"),
    ("Thread::Mutex", "initialize"),
    ("Thread::Queue", "initialize"),
    ("Thread::SizedQueue", "initialize"),
    ("Time", "_dump"),
    ("Time", "initialize"),
    ("Time", "initialize_copy"),
];

/// Whether the built-in `method` defined by `owner` is private there.
pub fn is_private(owner: &str, method: &str) -> bool {
    PRIVATE_BUILTIN_METHODS
        .binary_search_by(|(o, m)| (*o, *m).cmp(&(owner, method)))
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_for_binary_search() {
        assert!(PRIVATE_BUILTIN_METHODS.windows(2).all(|w| w[0] < w[1]));
    }

    #[test]
    fn kernel_functions_are_private_and_object_methods_are_not() {
        assert!(is_private("Kernel", "puts"));
        assert!(is_private("BasicObject", "initialize"));
        assert!(!is_private("Kernel", "freeze"));
        assert!(!is_private("Kernel", "respond_to?"));
    }
}
